### ISSUE TITLE
Random OCIError: ORA-03114 and ORA-03135 after upgrade from 2.1.8 to 2.2.0

### ISSUE THREAD

**Issue by duffyjp** [kubo/ruby-oci8#102]
After upgrading I'm getting the following two errors sporadically:

```
UNCAUGHT EXCEPTION IMPORTING HRS JOB HISTORY: OCIError: ORA-03114: not connected to ORACLE:

UNCAUGHT EXCEPTION IMPORTING UWMF JOB HISTORY: OCIError: ORA-03135: connection lost contact
```

Occurs on both OSX 10.10 Yosemite and Ubuntu Server 14.04 LTS.

Here are partial stack traces for each:

```
OCIError: ORA-03114: not connected to ORACLE
---------------
stmt.c:82:in oci8lib_210.so
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/ruby-oci8-2.2.0/lib/oci8/cursor.rb:28:in `initialize'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/ruby-oci8-2.2.0/lib/oci8/oci8.rb:179:in `new'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/ruby-oci8-2.2.0/lib/oci8/oci8.rb:179:in `parse_internal'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/ruby-oci8-2.2.0/lib/oci8/oci8.rb:172:in `parse'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:109:in `prepare'
/var/www/pims_app/
 shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:29:in `block in exec_query'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1261:in `log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:25:in `exec_query'
/var/www/pims_app/shared/bundle/rub
 y/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:253:in `select'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation/finder_methods.rb:338:in `find_with_associations'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:604:in `exec_queries'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:486:in `load'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:231:in `to_a'
```

```
OCIError: ORA-03135: connection lost contact
------------------
stmt.c:243:in oci8lib_210.so
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/ruby-oci8-2.2.0/lib/oci8/cursor.rb:126:in `exec'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:151:in `exec'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:45:in `block in exec_query'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abs
 tract_adapter.rb:367:in `log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1261:in `log'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:25:in `exec_query'
/var/www/pims_app/shared/bundle/ruby/2.1.0/bundler/gems/oracle-enhanced-d2025d45aea6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:253:in `select'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/querying.rb:39:in `find_by_sql'

/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:604:in `exec_queries'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:486:in `load'
/var/www/pims_app/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/relation.rb:231:in `to_a'
```

Please let me know if there is anything else I can provide to help.

**Comment by kubo** [comment]
I'm checking changes between 2.1.8 and 2.2.0.2.
I found a handle leak. I think that it causes memory increase while a process is running, but it isn't related to the issue.
Well, sorry, I have no time now to check it.

**Comment by kubo** [comment]
Could you post more detailed information?
* Oracle client version
* Platform of Oracle client
* Oracle server version
* Platform of Oracle server
* ruby version
* ruby version used for ruby-oci8 2.1.8 if you upgraded ruby when upgrading ruby-oci8.

I wrote that I had found a handle leak. But it gets problems only when OCI8#ping used and the Oracle client version is Oracle 10gR1.

**Comment by duffyjp** [comment]
Sure.  First, here's where I started, which works fine:

#### Workstation: Mac OSX 10.10, Ruby OCI8 2.1.8,  Ruby 2.1.5, Rails 4.1.5
```bash
$ ./genezi -v
Client Shared Library 64-bit - 11.2.0.4.0

System name:	Darwin
Release:	14.5.0
Version:	Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Machine:	x86_64

Operating in Instant Client mode.

$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

```

#### Web Server: Ubuntu 12.04.5 LTS, Ruby OCI8 2.1.8,  Ruby 2.1.5, Rails 4.1.5
```bash
$ ./genezi -v
Client Shared Library 64-bit - 11.2.0.3.0

System name:	Linux
Release:	3.2.0-90-generic
Version:	#128-Ubuntu SMP Fri Aug 14 21:43:58 UTC 2015
Machine:	x86_64

Operating in Instant Client mode.

$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
```


#### Oracle Server
```sql
select * from v$version;
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
PL/SQL Release 11.2.0.3.0 - Production
"CORE	11.2.0.3.0	Production"
TNS for IBM/AIX RISC System/6000: Version 11.2.0.3.0 - Production
NLSRTL Version 11.2.0.3.0 - Production
```

The only thing I changed was to upgrade to ruby-oci8 2.2.0.  Rolling back to 2.1.8 worked fine, but won't support OS X El Capitan due to the new DYLD_* limitation.

よろしくお願いします

**Comment by kubo** [comment]
Thank you!
Could you check out `266143b`, `58423f0`, `663fe57` and `782fb3f` and test them until working revision is found?

If you use bundler, change `Gemfile` as follows, run `bundle` and check whether it works fine with your application.
```ruby
gem 'ruby-oci8',    github: 'kubo/ruby-oci8', ref: '266143b'
```
If it doesn't work fine, replace `266143b` with `58423f0`, run `bundle` and check again.
If it doesn't work fine also, try `663fe57` and `782fb3f` until it works fine.

If you don't use bundler and use gem, checkout `266143b` and install it as follows
```shell
$ git clone https://github.com/kubo/ruby-oci8.git
$ cd ruby-oci8
$ git checkout 266143b
$ gem uninstall ruby-oci8
$ gem build ruby-oci8.gemspec # creates ruby-oci8-2.2.0.gem, which is older then the released 2.2.0.
$ gem install ./ruby-oci8-2.2.0.gem # installs the gem created by the previous command.
```
If it doesn't work fine with your application, check out `58423f0` and check again.
```shell
$ git checkout 58423f0
$ gem uninstall ruby-oci8
$ gem build ruby-oci8.gemspec # creates ruby-oci8-2.1.8.gem, which is newer then the released 2.1.8.
$ gem install ./ruby-oci8-2.1.8.gem # installs the gem created by the previous command.
```
If it doesn't work fine also, try `663fe57` and `782fb3f` until it works fine.

I'll install ruby 2.1.5 and check whether it works fine with ruby-oci8 2.2.0 by myself too.
I have not tested ruby-oci8 with ruby 2.1.5.

**Comment by duffyjp** [comment]
Here are my results.  I'm running a large import script which pulls from oracle into a local MySQL.  It doesn't always fail at the same point, but does seem to fail after a fairly consistent period of time.

| Revision | Commited   |  Result                          |  OS             |   Ruby     | Execution Time  |
|-------------|----------------- |-------------------------------|-----------------|--------------|-----------------------|
| 266143b |  2015-10-04 | OCIError: ORA-03114 | El Capitan  | 2.1.5        |  11 minutes        |
| 266143b |  2015-10-04 | OCIError: ORA-03114 | El Capitan  | 2.2.3        | 9 minutes            |
| 58423f0  |  2015-06-21 | OCIError: ORA-03114 | Yosemite    | 2.1.5       |   10 minutes       | 
| 58423f0  |  2015-06-21 | OCIError: ORA-03114  | Yosemite    | 2.2.3       |   9 minutes         | 
| 663fe57 |   2015-05-23 | OCIError: ORA-03114  | Yosemite    | 2.2.3       |   10 minutes        | 
| 782fb3f |    2015-05-22 |  OCIError: ORA-03114 |  Yosemite  | 2.1.5        |  8 minutes   |
| 782fb3f |   2015-05-22  |  OCIError: ORA-03114 |  Yosemite  | 2.2.3        |  10 minutes      | 
| 6d2e0a5 | 2015-04-04 |   Success                       | Yosemite   | 2.1.5        |  85 minutes    |

It appears the first commit after 2.1.8 (782fb3f) switches to the ruby 2 style threading.  I don't know much about that, but I read a little bit on it on the Passenger issue tracker.  I do make use of threading in my application.  I do so with the Parallel gem.  Here's an example:

```ruby
Parallel.each(Hrs::Person.all, in_processes: MAX_PROCESSES) do |person|
  person.import_jobs
end
```
```Hrs::Person``` is a model referencing an Oracle database, and ```MAX_PROCESSES``` is between 3 and 12 on different systems we use here.

Thank you so much for your help.

**Comment by duffyjp** [comment]
### Updating Parallel from 1.4.1 to 1.6.1
| Revision  | Committed | Result | OS | Ruby | Execution |
|--------------|----------------|-----------|------|--------|---------------|
| 782fb3f	 |  2015-05-22	| OCIError: ORA-03114	| Yosemite	| 2.1.5	|  9 minutes

Nope, that didn't work.  :smile:

**Comment by kubo** [comment]
Thanks a lot!
That is valuable information. I realized what I should focus on.

**Comment by kubo** [comment]
I looked 782fb3f closely and found two bugs. But, IMO, both bugs (2581d58 and 741c70f)  are not related to the issue.

Could you check the latest code in github just to be sure?
If you use bundler, put the following line in `Gemfile`, delete `Gemfile.lock` and run `bundle` to fetch the latest commit.
```
gem 'ruby-oci8',    github: 'kubo/ruby-oci8'
```
Or use the following gem.
```shell
$ git clone https://github.com/kubo/ruby-oci8.git
$ cd ruby-oci8
# or just run 'git pull' in this directory if you have already cloned it.
$ gem uninstall ruby-oci8
$ gem build ruby-oci8.gemspec
$ gem install ./ruby-oci8-2.2.0.2.gem
```
If it runs successfully, use it for a while. I'll release ruby-oci8 2.2.1 next weekend.

If it gets failure, could you revert files changed by 782fb3f and check whether it works successfully?

Revert `ext/oci8/extconf.rb` and check it at first.
```shell
$ git checkout 782fb3f
$ wget https://bintray.com/artifact/download/kubo/generic/ruby-oci8-2.1.8.tar.gz # or curl -OL https://bintray.com/artifact/download/kubo/generic/ruby-oci8-2.1.8.tar.gz
$ tar xvfz ruby-oci8-2.1.8.tar.gz
$ cp ruby-oci8-2.1.8/ext/oci8/extconf.rb ext/oci8/extconf.rb 
$ gem uninstall ruby-oci8
$ gem build ruby-oci8.gemspec
$ gem install ./ruby-oci8-2.1.8.gem
```
If you use bundler, use the following line in `Gemfile` to use the gem created above.
```
gem 'ruby-oci8',    '= 2.1.8'
```
If it gets failure, revert `ext/oci8/oci8.h` next.
```shell
$ cp ruby-oci8-2.1.8/ext/oci8/oci8.h ext/oci8/oci8.h
$ gem uninstall ruby-oci8
$ gem build ruby-oci8.gemspec
$ gem install ./ruby-oci8-2.1.8.gem
```
If it also gets failure, revert the following files one by one.
* ext/oci8/apiwrap.c.tmpl
* ext/oci8/encoding.c
* ext/oci8/env.c
* ext/oci8/lob.c
* ext/oci8/oci8.c
* ext/oci8/oci8lib.c
* ext/oci8/ocinumber.c
* ext/oci8/thread_util.c
* ext/oci8/thread_util.h
* lib/oci8/bindtype.rb
* lib/oci8/oci8.rb
* lib/oci8/encoding-init.rb

Sorry for the bothering task.
Otherwise, could you make a script to reproduce the issue?
If it can be reproduced in my machine, I can check it by myself.

I get `ORA-03113: end-of-file on communication channel` by the following script.
But it disappears when `p $!.backtrace` is added after `p $!` to get the backtrace.
I cannot imagine why just adding one line in a rescue block suppress exceptions.
```ruby
require 'parallel'
require 'oci8'
require 'active_record'

p OCI8::VERSION
p OCI8::oracle_client_version

ActiveRecord::Base.establish_connection(
  adapter:  "oracle_enhanced",
  database: "//localhost/ora121",
  username: "ruby",
  password: "oci8",
)

seq = 1.upto 10

class User < ActiveRecord::Base
end

thr1 = Thread.new do
  Thread.abort_on_exception = true
  loop do
    Parallel.each(seq, in_threads: 3) do
      begin
        p User.all
      rescue Exception
        p $!
      end
    end
  end
end

thr2 = Thread.new do
  Thread.abort_on_exception = true
  loop do
    Parallel.each(seq, in_processes: 3) do
      begin
        p User.all
      rescue Exception
        p $!
      end
    end
  end
end

thr1.join
thr2.join
```

**Comment by duffyjp** [comment]
## Success!

 I pulled the latest commit, and ran my script:

| Revision  | Committed | Result | OS | Ruby | Execution |
|--------------|----------------|-----------|------|--------|---------------|
| 2581d58  | 2015-10-26 | Success  | Yosemite	| 2.1.5	|  84 minutes

I will continue working with this revision in development and follow up if I run into any issues.  So far so good!  I'll also try the commit on my El Capitan computer and with Ruby 2.2.3 and update this comment when the results are in.

Thank you!

**Comment by kubo** [comment]
@duffyjp 
Ruby-oci8 2.2.1 was released. Could you check it?

**Comment by duffyjp** [comment]
So far so good!  

| Revision  | Committed | Result | OS | Ruby | Execution |
|--------------|----------------|-----------|------|--------|---------------|
| 9f7a283  | 2015-11-01 | Success  | El Capitan	| 2.1.5	|  77 minutes
| 9f7a283  | 2015-11-01 | Success  | El Capitan	| 2.2.3	|  86 minutes

**Comment by duffyjp** [comment]
I've been using 2.2.1 for a few days now, and it's been working great!  Sorry I could never provide you a specific code sample or a test to run.  I only interface with Oracle databases outside my department.

If you're satisfied, I'd call this issue closed!  :smile:

**Comment by duffyjp** [comment]
It's so funny when I google an error and see my own post from 2015. :) 

I'm running into the same error message on a new Rails 5.2 project. It's my first 5.2 with oracle, our main stuff is still on 5.1.  This time it's only happening in Rake tasks. I have individual tasks to do imports against each server.  If you call any one of them it works fine.  I have an `import:all` that just calls each in order.  The instant it hits the task for the second server (in either order) the connection for that server is gone.  If I run the identical commands in the rails console it works.

Here's the task:

```ruby
namespace :import do
  desc "Import Everything"

  task all: :environment do |task|

    puts "Importing A".blue
    Rake::Task['import:a'].invoke

    puts "Importing B".blue
    Rake::Task['import:b'].invoke

    puts "Done!".green

  end
end
```


* rails (5.2.1)
* rake (12.3.1)
* ruby-oci8 (2.2.6.1)

Instant Client Info:
```              
🍔  oracle 10:31$ ./genezi -v
Client Shared Library 64-bit - 12.2.0.1.0

System name:	Darwin
Release:	17.7.0
Version:	Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64
Machine:	x86_64

Operating in Instant Client mode.
```

Server A: "Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production"
Server B: "Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production"

Actual Message:
```
OCIError: ORA-03135: connection lost contact
Process ID: 49218008
Session ID: 787 Serial number: 140664473946024
stmt.c:243:in oci8lib_230.bundle
```

My gut feeling says it's most likely a change in Rails 5.1 to 5.2 causing the issue, but nothing is jumping out at me.  My `rake` and `ruby` versions are the same between 5.1 and 5.2.  Let me know if there's anything else I can provide that might help.
