### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JDominator** [kubo/ruby-oci8#104]
I'm having trouble figuring out how to bind an array to a variable with a sys.odcinumberlist type.

I figured NamedType would be the way to go, but I can't figure out how to use it.
http://www.rubydoc.info/gems/ruby-oci8/2.0.6/OCI8/BindType/NamedType#create-class_method

How do you use custom types?

**Comment by kubo** [comment]
Use it as follows.
```ruby
class OdciNumberList < OCI8::Object::Base
  set_typename 'sys.odcinumberlist'
end

# input parameter
cursor = conn.parse('begin ... end;')
cursor.bind(1, [1,2,3], OdciNumberList)  # bind the first place holder as sys.odcinumberlist
cursor.exec

# output paramter
cursor = conn.parse('begin ... end;')
cursor.bind(1, nil, OdciNumberList)  # bind the first place holder as sys.odcinumberlist
cursor.exec
obj = cursor[1] # => instance of OdciNumberList
obj && obj.to_ary # => array of integers
```
OCI8::BindType::NamedType is used internally when a subclass of OCI8::Object::Base is bound.

Well, I have not checked whether it runs... I forget how to get an array from output parameters.
I'll check it and update the document later.

**Comment by JDominator** [comment]
@kubo, you are a saint. THANK YOU... seriously. I would have never figured that out.

Our developers wrote something that just strings a bunch of binds together and wraps it a select like so
```sql
... where ID in (select * from table(sys.odcinumberlist(:bind1, :bind2, ... :bind999)))
```
but that doesn't make any sense... and the optimizer doesn't know how to peek properly when it's like that.

So I'm going to propose updating it to use a bind that has the numberlist type.

```ruby
id_array=[]
id_array<<1000
id_array<<1001
id_array<<1002
cursor = @connection_id.parse("SELECT * FROM table(:my_ids)")
cursor.bind_param(':my_ids', id_array, OdciNumberList)
```

```ruby
cursor = @connection_id.parse("SELECT * FROM my_table where id in (select * from table(:account_id))")
cursor.bind_param(':account_id', account_id_array, OdciNumberList)
```

Thank you again... I may pester you again sometime oh wise one ;)
I use oci8 for a handful of things, but the online doc can only take me so far.
