### ISSUE TITLE
Can't start Rails with ruby-oci8 & activerecord-oracle_enhanced-adapter after upgrading to El Capitan

### ISSUE THREAD

**Issue by istrasci** [kubo/ruby-oci8#106]
Hello, I'm running a Rails 4.2.4 application.  I just upgraded my OSX to El Capitan and now the Rails server will not start.  I re-installed Oracle instantclient 11.2, and tried to fix the identification and names with `fix_oralib.rb` as described [HERE](https://github.com/kubo/ruby-oci8/issues/99#issuecomment-147047229), [HERE](https://github.com/kubo/fix_oralib_osx), and [HERE](http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-on-osx.md#Install_Oracle_Instant_Client_Manually).

The error it gives me is ([pastebin of full stack trace](http://pastebin.com/t0Vi4j3t))

    /Users/istrasci/.rvm/gems/ruby-2.2.3/gems/activerecord-oracle_enhanced-adapter-1.6.3/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:7:in `rescue in <top (required)>': ERROR: 'dlopen(/Users/istrasci/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.0.2/oci8lib_220.bundle, 9): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1 (LoadError)
      Referenced from: /Users/istrasci/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.0.2/oci8lib_220.bundle
      Reason: image not found - /Users/istrasci/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.0.2/oci8lib_220.bundle'. ActiveRecord oracle_enhanced adapter could not load ruby-oci8 library. You may need install ruby-oci8 gem.

I'm not sure if the culprit is ruby-oci8 or activerecord-oracle_enhanced-adapter (or both).  Since it says `Library not loaded`, it seems like it's just not finding the right lib file, but I thought the `fix_oralib` was linking the correct names.  Can you offer any insight?  I'm using

    ruby-2.2.3
    rails-4.2.4
    activerecord-oracle_enhanced-adapter-1.6.(2 or 3)
    ruby-oci8-2.2.0.2

**Comment by kubo** [comment]
> Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1

If `libclntsh.dylib.11.1` is installed in `/opt/oracle/instantclient_11_2`, run the following command.
```shell
ruby fix_oralib.rb --ic_dir=/opt/oracle/instantclient_11_2 /Users/istrasci/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.0.2/oci8lib_220.bundle
```
IMO, you installed ruby-oci8 before fixing library identification and install names in Oracle libraries.

**Comment by istrasci** [comment]
@kuboさん、that worked!  ホンマに助かりました！ご多忙のところ、お邪魔してすみませんでした。orz
