### ISSUE TITLE
gem install ruby-oci8 with Set the environment variable DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by lilichen1** [kubo/ruby-oci8#108]
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

i have set orcale_path ,i can connect orcale DB which its using Navicate
but i got those

Error Message:
Set the environment variable DYLD_LIBRARY_PATH, DYLD_FALLBACK_LIBRARY_PATH or
OCI_DIR to point to the Instant client directory.

If DYLD_LIBRARY_PATH or DYLD_FALLBACK_LIBRARY_PATH is set, the environment
variable must be set at runtime also.

can you tell me what can i do?

**Comment by kubo** [comment]
Could you post the information I requested in https://github.com/kubo/ruby-oci8/issues/48#issuecomment-153337162?

**Comment by kubo** [comment]
This issue was closed because of no response.
