### ISSUE TITLE
require': cannot load such file -- oci8 (LoadError) -on mac OSX

### ISSUE THREAD

**Issue by dineshperomy** [kubo/ruby-oci8#109]
I am trying to establish the odbc connectivity via ruby-oci8 (2.2.1) but I am getting the error as 

"require': cannot load such file -- oci8 (LoadError)"

My scripts looks like..

require 'oci8'
oci = OCI8.new('xxx',xxx,xxx)

But successfully installed the ruby-oci8 successfully into my machine by following instruction given in the pages

http://stackoverflow.com/questions/11894194/how-to-install-ruby-oci8?answertab=votes#tab-top

http://www.rubydoc.info/github/kubo/ruby-oci8/master/file/docs/install-on-osx.md

Please help me to sort out this issue.

**Comment by duffyjp** [comment]
If you type ```gem list ruby-oci8``` in the same folder as your script, does it show ruby-oci8 installed?  

```bash
gem list ruby-oci8
*** LOCAL GEMS ***
ruby-oci8 (2.1.8)
```

```bash
$ irb
2.1.5 :001 > require 'oci8'
 => true 
```

Do you use RVM or rbenv?  If you got ruby-oci8 installed on one ruby and then try to load it from another you'll get the LoadError you described.  I'm on linux ATM, but I use OSX at work.  Once you get it installed, it's the same.

**Comment by dineshperomy** [comment]
Thanks for your input. But Now i am getting library not loaded error as shown below

/Users/xxx/.rvm/rubies/ruby-2.2.3/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/xxx/Desktop/Test_BDD/features/step_definitions/dbconnection.rb
/opt/oracle/instantclient_11_2
/Users/xxxx/.rvm/gems/ruby-2.2.3/gems/ruby-oci8-2.2.1/lib/oci8.rb:72:in `require': dlopen(/Users/xxx/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.1/oci8lib_220.bundle, 9): Library not loaded: /ade/b/3071542110/oracle/rdbms/lib/libclntsh.dylib.11.1 (LoadError)
  Referenced from: /Users/xxx/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.1/oci8lib_220.bundle
  Reason: image not found - /Users/xxx/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.1/oci8lib_220.bundle
	from /Users/xxxx/.rvm/gems/ruby-2.2.3/gems/ruby-oci8-2.2.1/lib/oci8.rb:72:in `<top (required)>'
	from /Users/xxx/Desktop/Test_BDD/features/step_definitions/dbconnection.rb:6:in `require'
	from /Users/xxx/Desktop/Test_BDD/features/step_definitions/dbconnection.rb:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Test Info:
OS: Mac OSX(Yosemite)
ruby version:tried with 2.1.5 and 2.2.3

Ref:
http://stackoverflow.com/questions/11894194/how-to-install-ruby-oci8?answertab=votes#tab-top

http://www.rubydoc.info/github/kubo/ruby-oci8/master/file/docs/install-on-osx.md

Your help highly appreciated

**Comment by kubo** [comment]
Set DYLD_LIBRARY_PATH.
If libclntsh.dylib.11.1 is in /opt/oracle/instantclient_11_2
```shell
$ export DYLD_LIBRARY_PATH=/opt/oracle/instantclient_11_2
```

If you don't want to set DYLD_LIBRARY_PATH,
```shell
$ cd /opt/oracle/instantclient_11_2
$ curl -O https://raw.githubusercontent.com/kubo/fix_oralib_osx/master/fix_oralib.rb
$ ruby fix_oralib.rb
$ ruby fix_oralib.rb /Users/xxx/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/ruby-oci8-2.2.1/oci8lib_220.bundle
```

**Comment by dineshperomy** [comment]
Thanks a lot Kubo. 

DYLD_LIBRARY_PATH path is already set up in my machine but that didn't work as per the expectation.
But your second option worked fine. Thanks a lot quick for your quick response.

**Comment by derick** [comment]
Thank you Kubo.  Running your script there did the trick.

**Comment by nitashah** [comment]
Hi i have same issue but fix_oralib is no longer working. it says its not available for later versions
