### ISSUE TITLE
oci8 does not appear to support :SYSDG, SYSBACKUP, etc connect as mode

### ISSUE THREAD

**Issue by dougxn** [kubo/ruby-oci8#110]
It would appear that oci8 doesn't support connect to oracle as SYSDG. This is new in Oracle 12c and allows connection to standby's and perform limit oreperations.

**Comment by dougxn** [comment]
/*------------------------Authentication Modes-------------------------------*/
#define OCI_MIGRATE         0x00000001            /* migratable auth context */
#define OCI_SYSDBA          0x00000002           /* for SYSDBA authorization */
#define OCI_SYSOPER         0x00000004          /* for SYSOPER authorization */
#define OCI_PRELIM_AUTH     0x00000008      /* for preliminary authorization */
#define OCIP_ICACHE         0x00000010             /* Private OCI cache mode */
#define OCI_AUTH_RESERVED_1 0x00000020                           /* reserved */
#define OCI_STMT_CACHE      0x00000040            /* enable OCI Stmt Caching */
#define OCI_STATELESS_CALL  0x00000080         /* stateless at call boundary */
#define OCI_STATELESS_TXN   0x00000100          /* stateless at txn boundary */
#define OCI_STATELESS_APP   0x00000200    /* stateless at user-specified pts */
#define OCI_AUTH_RESERVED_2 0x00000400                           /* reserved */
#define OCI_AUTH_RESERVED_3 0x00000800                           /* reserved */
#define OCI_AUTH_RESERVED_4 0x00001000                           /* reserved */
#define OCI_AUTH_RESERVED_5 0x00002000                           /* reserved */
#define OCI_SYSASM          0x00008000           /* for SYSASM authorization */
#define OCI_AUTH_RESERVED_6 0x00010000                           /* reserved */
#define OCI_SYSBKP          0x00020000        /* for SYSBACKUP authorization */
#define OCI_SYSDGD          0x00040000            /* for SYSDG authorization */
#define OCI_SYSKMT          0x00080000            /* for SYSKM authorization */

**Comment by kubo** [comment]
Thank for notifying me.

Here is a patch but I have not tested it.
I'll check it later and commit it after refactoring.
```
diff --git a/lib/oci8/oci8.rb b/lib/oci8/oci8.rb
index 2e226b5..2954a6e 100644
--- a/lib/oci8/oci8.rb
+++ b/lib/oci8/oci8.rb
@@ -114,6 +114,21 @@ class OCI8
         raise "SYSASM is not supported on Oracle version #{OCI8.oracle_client_version}"
       end
       mode = OCI_SYSASM
+    when :SYSBACKUP
+      if OCI8.oracle_client_version < OCI8::ORAVER_12_1
+        raise "SYSBACKUP is not supported on Oracle version #{OCI8.oracle_client_version}"
+      end
+      mode = 0x00020000 # OCI_SYSBKP in oci.h
+    when :SYSDG
+      if OCI8.oracle_client_version < OCI8::ORAVER_12_1
+        raise "SYSDG is not supported on Oracle version #{OCI8.oracle_client_version}"
+      end
+      mode = 0x00040000 # OCI_SYSDGD in oci.h
+    when :SYSKM
+      if OCI8.oracle_client_version < OCI8::ORAVER_12_1
+        raise "SYSKM is not supported on Oracle version #{OCI8.oracle_client_version}"
+      end
+      mode = 0x00080000 # OCI_SYSKMT in oci.h
     when nil
       # do nothing
     else
```

**Comment by kubo** [comment]
I committed f20dfe2bd76479dc8d58dae05c533f52dc355557.
The next version of ruby-oci8 supports :SYSBACKUP, :SYSDG and :SYSKM.
Thanks for your reporting this issue.
