### ISSUE TITLE
bundle.require does not work without manual require because of non standart gem name

### ISSUE THREAD

**Issue by PositiveAlex** [kubo/ruby-oci8#114]
Please, refer to https://github.com/bundler/bundler/issues/4190

I need to write:

`gem 'ruby-oci8', :require => 'oci8'`

to be able to autorequire this module in `bundle.require`

**Comment by kubo** [comment]
This issue will be easily fixed by adding `ruby-oci8.rb` containing `require 'oci8'`.
However I'm not sure whether I should add it.
If there were no workaround, I definitely done.
But there is a workaround as you wrote.
Give me time to think about it.

**Comment by PositiveAlex** [comment]
It is not a problem for me)

Anyway, just to think about it, gem naming convention:
http://guides.rubygems.org/name-your-gem/

But it is impossible to rename it, because everyone has to rewrite it in
gemfiles and/or in project files, so renaming is not good solution.

However, gemfile's require option is for that situations of non standart
naming.

So... I dont really think we can do something with oci8, actually...

Posted issue just to inform you...
Thanks anyway

чт, 31 дек. 2015, 17:37, Kubo Takehiro <notifications@github.com>:

**Comment by kubo** [comment]
[ruby-oci8.rb](https://github.com/kubo/ruby-oci8/blob/master/lib/ruby-oci8.rb) was added. It just requires `oci8`.
