### ISSUE TITLE
Unable to load ruby-oci8 via require 'oci8' from cucumber command line

### ISSUE THREAD

**Issue by rab0309** [kubo/ruby-oci8#118]
I'm not able to load the ruby-oci8 gem using require 'oci8' from a libray file which gets invoked when running a cucumber test scenario from the command line.

Prior to installing RVM and the Ruby version listed below, this was working no problem (with all of the Oracle Instant Client setup, environment variables, etc...) using my mac's system version of Ruby (version -> ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]).  After switching over, I am no longer able to load ruby-oci8 through cucumber.  I'm at a bit of a loss for what to check / try next.

Config / Setup:
- Mac OS El Capitan
- RVM is installed
- Ruby Version -> ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
- ruby-oci8 gem version -> ruby-oci8 (2.2.1)
- cucumber gem version -> cucumber (2.3.2)
- Everything is 64-bit.

Gem List:
$ gem list ruby-oci8
**\* LOCAL GEMS ***
ruby-oci8 (2.2.1)

From IRB:
$ irb
2.2.1 :001 > require 'oci8'
Warning: NLS_LANG is not set. fallback to US7ASCII.
 => true

From Cucumber:
$ cucumber -t @1
cannot load such file -- oci8 (LoadError)
/$HOME/base_ucs_db_connect.rb:1:in `require'
/$HOME/base_ucs_db_connect.rb:1:in`<top (required)>'
/$HOME/base_ucs_db_ixn_query.rb:1:in `require_relative'
/$HOME/base_ucs_db_ixn_query.rb:1:in`<top (required)>'
/$HOME/ixn_id_by_subject_query.rb:1:in `require_relative'
/$HOME/ixn_id_by_subject_query.rb:1:in`<top (required)>'
/$HOME/features/support/env.rb:11:in `require_relative'
/$HOME/features/support/env.rb:11:in`<top (required)>'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/rb_support/rb_language.rb:96:in`load_code_file'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:84:in`block in load_files!'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in `each'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime/support_code.rb:83:in`load_files!'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:254:in `load_step_definitions'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:62:in`run!'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in `execute!'
/$HOME/.rvm/gems/ruby-2.2.1/gems/cucumber-2.3.2/bin/cucumber:8:in`<top (required)>'
/$HOME/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `load'
/$HOME/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in`<main>'
/$HOME/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/$HOME/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in`<main>'

Let me know if more information is needed.

**Comment by kubo** [comment]
I have no idea. I know nothing about cucumber.
IMO, this isn't a ruby-oci8 specific issue.
Could you install other gem by `gem install ???` and use the gem via cucumber?

**Comment by kubo** [comment]
close this issue because of no response.
