### ISSUE TITLE
Timeout Parameters in v2.2.2

### ISSUE THREAD

**Issue by mofahead** [kubo/ruby-oci8#122]
Hi, I see in the docs that timeout parameters are available since ruby-oci8 2.2.2, however it appears that this is a future release. Is there a way to access this functionality in 2.2.1, or is it safe in your opinion to install the newest build from github? Thanks so much for your help!

**Comment by kubo** [comment]
IMO, the current github code is safe.
However it may become unstable for a while after implementing #119.

**Comment by mofahead** [comment]
Thank you, I will give it a try.
