### ISSUE TITLE
Logon Denied for Mac OSX El Capitan with Instant Client x64-12.1.0.2.0

### ISSUE THREAD

**Issue by erluti** [kubo/ruby-oci8#133]
Doing a basic connection with OCI8.new and executing a select statement is throwing this exception:
```
oci8.c:694:in oci8lib_210.bundle: ORA-01017: invalid username/password; logon denied (OCIError)
	from /Users/pbecker/.rvm/gems/ruby-2.1.5/gems/ruby-oci8-2.2.1/lib/oci8/oci8.rb:151:in `initialize'
```
I can connect via other tools (like SqlDeveloper), but in ruby I get the logon denied error.

**Comment by kubo** [comment]
> ORA-01017: invalid username/password

How did you set username and password?
The following commands work for me:
```shell
ruby -roci8 -e "OCI8.new('ruby/oci8@//192.168.0.3/ora121').exec('select * from dual') do |row| puts row.join(','); end"
ruby -roci8 -e "OCI8.new('ruby', 'oci8', '//192.168.0.3/ora121').exec('select * from dual') do |row| puts row.join(','); end"
```
Environment:
* OS X 10.10.5 yosemite
* ruby 2.3.1
* Oracle Instant Client x64 12.1.0.2.0

**Comment by erluti** [comment]
Both of those commands returned the same password error for me.

- OS X 10.11.5 El Capitan (Sorry I said Yosemite, updated title to reflect)
- ruby 2.1.5
- Oracle Instant Client x64 12.1.0.2

I also tried x32 of that Instant Client.  Also tried 11.2.0.4.0 (64-bit).
I also tried with fix_oralib.rb on both 64 bit versions.
I also tried installing via homebrew and manually.
Posted here because I have no idea what else to try.

**Comment by kubo** [comment]
Could you try sqlplus on the same OS X?
If it works, I'll port [ocidump](https://github.com/kubo/ocidump) to OS X tomorrow to check the difference of OCI function calls issued by sqlplus and ruby-oci8.

**Comment by erluti** [comment]
Looks like I'm getting the same error from SQLPlus.  I'll dig into this a bit more. Thanks!

**Comment by erluti** [comment]
Looks like there's an issue with Instant Client.  Here's some information about it here.  Good news is that the gem is okay!
https://blogs.oracle.com/opal/entry/using_oracle_on_os_x

**Comment by kubo** [comment]
FYI.
Instant Client for OS X was updated. This issue was fixed by Oracle.
http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html
