### ISSUE TITLE
Add support for OCILIB

### ISSUE THREAD

**Issue by jirutka** [kubo/ruby-oci8#152]
Is it possible to add support for [OCILIB](https://github.com/vrogier/ocilib) – Open source C and C++ library for accessing Oracle databases – as a replacement for proprietary oci8?

**Comment by kubo** [comment]
It may be possible but I won't add support for OCILIB.

OCILIB isn't a replacement for OCI(Oracle Call Interface). It is built on OCI and loads proprietary Oracle client libraries at runtime. If ruby-oci8 supports OCILIB in addition to OCI, it makes ruby-oci8 code complex and gains no merit. If ruby-oci8 drops OCI support and uses OCILIB instead, it makes ruby-oci8 code simple but may drop some ruby-oci8 features.
