### ISSUE TITLE
Question [Is ruby-oci8 support DRCP]

### ISSUE THREAD

**Issue by coolflighter** [kubo/ruby-oci8#165]
Dear Kubo

 Please do me a favor let me ask a question.
 There is a Ruby Program access DB with ruby-oci8 .
 The Ruby Program trigger hundreds of new connections very frequently ,
 and the connections also stay long time on db(from a few minutes to around 1 hour).
 I want to know Is DRCP can alleviate the concurrency issue caused by frequent connections ?
 Oracle version is 11.2.0.3 . If ruby-oci8 support DRCP,
 Can you give me some advice about How to configure ruby-oci8 & DRCP ?

Thank you very much.
menglong.zheng@oracle.com

**Comment by kubo** [comment]
As far as I checked, you can use DRCP by (1) enabling DRCP on server side and (2) connecting to the server by putting [POOLED](https://docs.oracle.com/cd/B28359_01/server.111/b28310/manproc004.htm#CHDIAIAA) in a easy connect string or in a TNS connect descriptor.
I don't know whether DRCP alleviates the issue. It depends on situations.

**Comment by coolflighter** [comment]
Dear Kubo

Thank you very much.
教えていただき、ありがとうございます。

**Comment by cjbj** [comment]
@kubo the app should also set a connection class name. Without a class you won't get full reuse of the DRCP pool.   The 'Purity' also needs to be considered too.  See:

https://github.com/php/php-src/blob/c8aa6f3a9a3d2c114d0c5e0c9fdd0a465dbb54a5/ext/oci8/oci8.c#L3189-L3208

**Comment by kubo** [comment]
@cjbj 
Thank you! I'll check it.

**Comment by pgundlupetvenkatesh** [comment]
I am getting this warning `C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.4.1-x64-mingw32/lib/oci8/oci8.rb:627: warning: method redefined; discarding old initialize` when I try to run rake tests on ruby-oci8 2.2.4.1 gem. When I downgrade the gem to 2.2.3 it runs without the warning. Hope it gets fixed soon.
