### ISSUE TITLE
Error Ignoring ruby-oci8-2.2.5.1 because its extensions are not built.

### ISSUE THREAD

**Issue by peteralfafara** [kubo/ruby-oci8#186]
Hi Kubo,

This is my second time asking for your expert advice. 

We've installed the latest version of ruby-oci8 but during run our scripts we encounter the following error? 

> Ignoring ruby-oci8-2.2.5.1 because its extensions are not built. Try: gem pristine ruby-oci8 --version 2.2.5.1 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- oci8 (LoadError) from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/sensu/embedded/bin/sqlcore.rb:28:in `<top (required)>' from /opt/sensu/embedded/bin/metrics-stale-transmission.rb:25:in `require_relative' from /opt/sensu/embedded/bin/metrics-stale-transmission.rb:25:in `<main>'

Any ideas on how to solve this? Thank you very much!

Regards,
Peter

**Comment by kubo** [comment]
Could you try `gem pristine ruby-oci8 --version 2.2.5.1` as the error message suggested?
You need to set `LD_LIBRARY_PATH` in advance. See [here](http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-full-client.md) or [here](http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/install-instant-client.md).

**Comment by peteralfafara** [comment]
Hi Kubo,

Thanks for the response. It turns out that there were just permission issues in the gem extension directory due to installing it using a non-root user. Just gave permission on the following directory

`chmod –R o+r /opt/sensu/embedded/lib/ruby/gems/2.4.0/extensions.` 

Thanks for the assistance once again!

Regards,
Peter
