### ISSUE TITLE
oci8 ORA-12154

### ISSUE THREAD

**Issue by avinashsa** [kubo/ruby-oci8#190]
Hi when I invoke the new I get the following error.

Has anyone seen this issue ?

oci8.c:561:in oci8lib_240.so: ORA-12154:  (OCIError)

**Comment by kubo** [comment]
Could you post more information when you post an issue?
* What version of ruby-oci8 do you use?
* What version of Oracle client and server do you use?
* What OS and the version do you use?
* Does it work using sqlplus?

The error `ORA-12154` is very common. It is caused by incorrectly configured network settings.
Could you connect to the server using sqlplus? If you can, it may be a ruby-oci8 issue. Otherwise, it isn't.

**Comment by avinashsa** [comment]
Hi,
sorry for the very brief info.. 
What version of ruby-oci8 do you use?
2.2.5.1 the latest version 

What version of Oracle client and server do you use?
I have tried with various.. 
The oracle server version is 10.2..0.4 so I have the same client at the moment but I have tried with 10-2.0.1 and 12
No joy

What OS and the version do you use?
I am running ruby on windows 10

Does it work using sqlplus?
Yes it used to work with sqlplus but after installing and uninstalling various versions I have broken the tns connection but the fully qulified version still works uname/passwd@server:port/SID

And it works using sql developer as well which uses the same combo above.

"It is caused by incorrectly configured network settings."
Which network settings do you mean the login credentials or something else ?

**Comment by avinashsa** [comment]
sorry server and instant client versions currently installed are 
Version 11.2.0.4.0  not 10.2.0.4 as mentioned in my previous comment

**Comment by avinashsa** [comment]
Oh I hate it when things suddenly start working without me fixing anything..

Anyway it works now.

Basically I did the following.
1> uninstalled all my clients
2> installed 11.2.0.4 instant client basic
3> instant client sql 
4> instant client sdk.
5> There was a problem with my NLS so I changed it (Maybe this was the key)
6> tested connecting through sqlplus  --success
7> tested connecting through oci8--success.

Maybe when I have time I will try break my nls again and test this and post the result to be sure if that was what was wrong with it.

**Comment by kubo** [comment]
> "It is caused by incorrectly configured network settings."
> Which network settings do you mean the login credentials/TNS/server settings or something else ?

I meant TNS settings. See [here](https://www.datavail.com/blog/ora-12154-tnscould-not-resolve-the-connect-identifier-specified/).

The issue is unrelated to NLS. I guess that you changed also TNS settings when you changed NLS.
