### ISSUE TITLE
libclntsh.so.12.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by peteralfafara** [kubo/ruby-oci8#191]
Hi Kubo,

My third time asking about oci8. Hopefully you can help me again on this one.

I've reinstalled oci8 on our machine but Sensu gets the following error upon script execution

> {"timestamp":"2018-04-17T10:27:38.138747+0000","level":"info","message":"publishing check result","payload":{"client":"OTM64Demo1","check":{"type":"metric","command":"/opt/sensu/embedded/bin/metrics-object-locks.rb -s 10","interval":600,"handle_when":{"reset":3600},"standalone":true,"payload-type":"json","environment":"OTM64DEMO1","name":"object-locks","issued":1523960858,"executed":1523960858,"duration":0.055,"output":"/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': libclntsh.so.12.1: cannot open shared object file: No such file or directory - /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so (LoadError)\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8.rb:107:in `<top (required)>'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'\n\tfrom /opt/sensu/embedded/bin/sqlcore.rb:32:in `<top (required)>'\n\tfrom /opt/sensu/embedded/bin/metrics-object-locks.rb:30:in `require_relative'\n\tfrom /opt/sensu/embedded/bin/metrics-object-locks.rb:30:in `<main>'\n","status":3}}}

Machine: Linux xxxxxxxx 3.8.13-55.1.2.el6uek.x86_64 #2 SMP Thu Dec 18 00:15:51 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
Oracle: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

I've installed oci8 using the following command:
`sudo env ORACLE_HOME=$ORACLE_HOME /bin/env LD_LIBRARY_PATH=/opt/oracle/12R12/lib: /opt/sensu/embedded/bin/gem install ruby-oci8`

Hoping for your response. Thanks!

Regards,
Peter

**Comment by kubo** [comment]
Could you post the output of the following commands?
```
ls -l /opt/oracle/12R12/lib
ldd /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so
# If readelf is installed,
readelf -d /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so  | grep rpath
```

**Comment by peteralfafara** [comment]
Hi Kubo, 

Thanks again for the immediate response. See below results:

ls -l /opt/oracle/12R12/lib:

> total 1066120
-rwxr-x---. 1 oracle oinstall     64892 May 23  2014 acfslib.pm
-rwxr-x---. 1 oracle oinstall     34936 May 23  2014 acfsroot.pl
-rwxr-x---. 1 oracle oinstall      2965 May 23  2014 acfstoolsdriver.sh
-rwxr-x---. 1 oracle oinstall     45386 Oct 23  2001 activation.jar
-rwxr-x---. 1 oracle oinstall      3541 May 23  2014 afddriverstate.pl
-rwxr-x---. 1 oracle oinstall      6887 May 23  2014 afdlib.pm
-rwxr-x---. 1 oracle oinstall     14245 May 23  2014 afdroot.pl
-rwxr-x---. 1 oracle oinstall      2802 May 23  2014 afdtoolsdriver.sh
-rwxr-x---. 1 oracle oinstall     53041 Nov 21  2013 asmcmdambr.pm
-rwxr-x---. 1 oracle oinstall     14233 Dec  4  2013 asmcmdamdu.pm
-rwxr-x---. 1 oracle oinstall    108899 Jun 11  2014 asmcmdanlz.pm
-rwxr-x---. 1 oracle oinstall     15785 Feb 25  2013 asmcmdattr.pm
-rwxr-x---. 1 oracle oinstall     41626 May 10  2014 asmcmdaudit.pm
-rwxr-x---. 1 oracle oinstall    173595 Jun 11  2014 asmcmdbase.pm
-rwxr-x---. 1 oracle oinstall     18895 Aug  7  2013 asmcmddiag.pm
-rwxr-x---. 1 oracle oinstall      7370 Jan 17  2007 asmcmd_disk_header_format
-rwxr-x---. 1 oracle oinstall    123618 Jun 11  2014 asmcmddisk.pm
-rwxr-x---. 1 oracle oinstall      7569 May 28  2013 asmcmdexceptions.pm
-rwxr-x---. 1 oracle oinstall     24076 Jun 11  2014 asmcmdglobal.pm
-rwxr-x---. 1 oracle oinstall     50719 Jan 30  2012 asmcmdparser.pm
-rwxr-x---. 1 oracle oinstall     51893 Feb 25  2013 asmcmdpasswd.pm
-rwxr-x---. 1 oracle oinstall    186150 Jun 11  2014 asmcmdshare.pm
-rwxr-x---. 1 oracle oinstall    132443 Jun 11  2014 asmcmdsys.pm
-rwxr-x---. 1 oracle oinstall     19546 Feb 25  2013 asmcmdtmpl.pm
-rwxr-x---. 1 oracle oinstall     47488 Mar  2  2014 asmcmdug.pm
-rwxr-x---. 1 oracle oinstall     56750 Jul  9  2013 asmcmdvol.pm
-rwxr-x---. 1 oracle oinstall      2223 Jul 18  2011 asmcmdxmlexceptions.pm
-rwxr-x---. 1 oracle oinstall    180926 Jun 11  2014 asmcommand.xml
-rwxr-x---. 1 oracle oinstall     39090 Jun 27  2014 classgen.jar
-rwxr-x---. 1 oracle oinstall   1169843 Nov  3  2015 clntshcore.map
-rwxr-x---. 1 oracle oinstall   4111721 Nov  3  2015 clntsh.map
-rwxr-x---. 1 oracle oinstall      4114 May 23  2014 facility.lis
-rwxr-x---. 1 oracle oinstall    473514 Dec  3  2010 http_client.jar
-rwxr-x---. 1 oracle oinstall     37948 Jun  9  2006 jcr-1.0.jar
-rwxr-x---. 1 oracle oinstall     56899 Sep 25  2000 jdev-rt.zip
-rwxr-x---. 1 oracle oinstall       115 Nov  3  2015 ldflags
-rwxr-x---. 1 oracle oinstall       132 Nov  3  2015 ldflagsO
-rwxr-x---. 1 oracle oinstall   1022104 Jul  1  2014 libacfs12.so
-rwxr-x---. 1 oracle oinstall    272513 Jul  1  2014 libafd12.so
-rwxr-x---. 1 oracle oinstall   1424630 Jul  7  2014 libagent12.a
-rwxr-x---. 1 oracle oinstall  10376839 Jun 30  2014 libagfw12.so
lrwxrwxrwx. 1 oracle oinstall        15 Nov  3  2015 libagtsh.so -> libagtsh.so.1.0
-rwxr-x---. 1 oracle oinstall   2530176 Nov  3  2015 libagtsh.so.1.0
-rwxr-x---. 1 oracle oinstall   8710630 Jun 19  2014 libanllexer12.so
-rwxr-x---. 1 oracle oinstall   1962032 Jul  7  2014 libasmclnt12.a
-rwxr-x---. 1 oracle oinstall   2187792 Jul  7  2014 libasmclntsh12.a
-rwxr-x---. 1 oracle oinstall   1670948 Jul  7  2014 libasmclntsh12.so
-rwxr-x---. 1 oracle oinstall     11378 Jul  7  2014 libasmperl12.a
-rwxr-x---. 1 oracle oinstall     13600 Jul  7  2014 libasmperl12.so
-rwxr-x---. 1 oracle oinstall     28454 Jul  7  2014 libavstub12.a
-rwxr-x---. 1 oracle oinstall  72954724 Jul  7  2014 libba12.so
-rwxr-x---. 1 oracle oinstall    415660 Jan  2  2014 libccme_asym.so
-rwxr-x---. 1 oracle oinstall    306612 May  6  2014 libccme_base_non_fips.so
-rwxr-x---. 1 oracle oinstall    555820 Jan  2  2014 libccme_base.so
-rwxr-x---. 1 oracle oinstall    812074 Nov 14  2013 libccme_ecc_accel_fips.so
-rwxr-x---. 1 oracle oinstall    780387 May  6  2014 libccme_ecc_accel_non_fips.so
-rwxr-x---. 1 oracle oinstall    461494 May  6  2014 libccme_ecc_non_fips.so
-rwxr-x---. 1 oracle oinstall    709631 Jan  2  2014 libccme_ecc.so
-rwxr-x---. 1 oracle oinstall   7408210 Jul  7  2014 libcell12.a
-rwxr-x---. 1 oracle oinstall   6791124 Jul  7  2014 libcell12.so
-rwxr-x---. 1 oracle oinstall   1631142 Jun 19  2014 libclib_jiio.so
-rwxr-x---. 1 oracle oinstall  11237440 Jul  7  2014 libclient12.a
lrwxrwxrwx. 1 oracle oinstall        43 Nov  3  2015 libclntshcore.so -> /opt/oracle/12R12/lib/libclntshcore.so.12.1
-rwxr-x---. 1 oracle oinstall   6991011 Nov  3  2015 libclntshcore.so.12.1
lrwxrwxrwx. 1 oracle oinstall        39 Nov  3  2015 libclntsh.so -> /opt/oracle/12R12/lib/libclntsh.so.12.1
lrwxrwxrwx. 1 oracle oinstall        12 Nov  3  2015 libclntsh.so.10.1 -> libclntsh.so
lrwxrwxrwx. 1 oracle oinstall        12 Nov  3  2015 libclntsh.so.11.1 -> libclntsh.so
-rwxrwxrwx. 1 oracle oinstall  58793581 Nov  3  2015 libclntsh.so.12.1
-rwxr-x---. 1 oracle oinstall         0 Jul  7  2014 libclntst12.a
-rwxr-x---. 1 oracle oinstall    632149 Jun 30  2014 libclsce12.so
-rwxr-x---. 1 oracle oinstall   1749282 Jun 30  2014 libclsr12.a
-rwxr-x---. 1 oracle oinstall    462362 Jun 30  2014 libclsra12.so
-rwxr-x---. 1 oracle oinstall  10085432 Jul  7  2014 libcommon12.a
-rwxr-x---. 1 oracle oinstall   5803698 Jun 17  2014 libcore12.a
-rwxr-x---. 1 oracle oinstall   2574084 Jun 17  2014 libcorejava.so
-rwxr-x---. 1 oracle oinstall      2638 Jan  2  2014 libcryptocme.sig
-rwxr-x---. 1 oracle oinstall    445946 Jan  2  2014 libcryptocme.so
-rwxr-x---. 1 oracle oinstall   6051402 Jun 19  2014 libctx12.a
-rwxr-x---. 1 oracle oinstall   1201840 Jun 19  2014 libctxc12.a
-rwxr-x---. 1 oracle oinstall     56964 Jun 19  2014 libctxs12.a
-rwxr-x---. 1 oracle oinstall      5612 May 23  2014 libcxaguard.so.5
-rwxr-x---. 1 oracle oinstall    196409 Jun 30  2014 libdbcfg12.so
-rwxr-x---. 1 oracle oinstall    196447 Jun 30  2014 libeons.so
-rwxr-x---. 1 oracle oinstall    617772 Nov  8  2011 libexpat.a
-rwxr-x---. 1 oracle oinstall       793 Nov  8  2011 libexpat.la
-rwxr-x---. 1 oracle oinstall    408282 Nov  8  2011 libexpat.so
-rwxr-x---. 1 oracle oinstall    408282 Nov  8  2011 libexpat.so.1
-rwxr-x---. 1 oracle oinstall    408282 Nov  8  2011 libexpat.so.1.5.2
-rwxr-x---. 1 oracle oinstall  34491692 Jul  7  2014 libgeneric12.a
-rwxr-x---. 1 oracle oinstall   1969487 Jun 30  2014 libgns12.so
-rwxr-x---. 1 oracle oinstall    346309 Jun 30  2014 libgnsjni12.so
-rwxr-x---. 1 oracle oinstall    610306 Jun 19  2014 libgx12.a
-rwxr-x---. 1 oracle oinstall  26442803 Jun 30  2014 libhasgen12.so
-rwxr-x---. 1 oracle oinstall     18027 Jun 30  2014 libheteroxa12.so
-rwxr-x---. 1 oracle oinstall    535598 Jul  7  2014 libhgosh12.a
-rwxr-x---. 1 oracle oinstall    206337 Jul  7  2014 libhgotrace12.so
-rwxr-x---. 1 oracle oinstall   4899672 May 23  2014 libimf.a
-rwxr-x---. 1 oracle oinstall    352351 May 23  2014 libintlc.so.5
-rwxr-x---. 1 oracle oinstall   2457778 Jun 18  2014 libipc1.a
-rwxr-x---. 1 oracle oinstall   1768370 Jun 18  2014 libipc1.so
-rwxr-x---. 1 oracle oinstall    116302 Dec  3  2013 libipp_bz2.a
-rwxr-x---. 1 oracle oinstall    103952 Dec  3  2013 libippcore.a
-rwxr-x---. 1 oracle oinstall   1342006 Jul  7  2014 libippcpemerged.a
-rwxr-x---. 1 oracle oinstall  10651828 Jul  7  2014 libippcpmerged.a
-rwxr-x---. 1 oracle oinstall    339570 Dec  3  2013 libippdcemerged.a
-rwxr-x---. 1 oracle oinstall   2652644 Dec  3  2013 libippdcmerged.a
-rwxr-x---. 1 oracle oinstall   4971338 Dec  3  2013 libippsemerged.a
-rwxr-x---. 1 oracle oinstall  47924222 Dec  3  2013 libippsmerged.a
-rwxr-x---. 1 oracle oinstall    129660 Dec  3  2013 libipp_z.a
-rwxr-x---. 1 oracle oinstall    534212 May 23  2014 libirc.a
lrwxrwxrwx. 1 oracle oinstall        36 Nov  3  2015 libjavavm12.a -> ../javavm/jdk/jdk6/lib/libjavavm12.a
-rwxr-x---. 1 oracle oinstall     35999 Jul  7  2014 libkubsagt12.so
-rwxr-x---. 1 oracle oinstall   1656964 Jun 18  2014 libldapclnt12.a
-rwxr-x---. 1 oracle oinstall     44498 Jun 18  2014 libldapjclnt12.a
-rwxr-x---. 1 oracle oinstall     75510 Jun 18  2014 libldapjclnt12.so
-rwxr-x---. 1 oracle oinstall    120118 Jun 19  2014 liblxled.a
-rwxr-x---. 1 oracle oinstall    889598 Jun 17  2014 liblzopro.a
-rwxr-x---. 1 oracle oinstall     82966 Jun 17  2014 libmgwagent.so
-rwxr-x---. 1 oracle oinstall      6020 Jul  7  2014 libmm.a
-rwxr-x---. 1 oracle oinstall    666598 Jun 18  2014 libmql1.a
-rwxr-x---. 1 oracle oinstall    544150 Jun 18  2014 libmql1.so
-rwxr-x---. 1 oracle oinstall   9169174 Nov  3  2015 libn12.a
-rwxr-x---. 1 oracle oinstall    113496 Jun 27  2014 libnbeq12.a
-rwxr-x---. 1 oracle oinstall    197030 Jun 26  2014 libncrypt12.a
-rwxr-x---. 1 oracle oinstall     96003 Jul  7  2014 libnfsodm12.so
-rwxr-x---. 1 oracle oinstall     29204 Jun 27  2014 libnhost12.a
-rwxr-x---. 1 oracle oinstall     84222 Jul  7  2014 libnid.a
-rwxr-x---. 1 oracle oinstall    195875 Jun 27  2014 libnjni12.so
-rwxr-x---. 1 oracle oinstall   1540260 Jun 27  2014 libnl12.a
-rwxr-x---. 1 oracle oinstall    329216 Jun 27  2014 libnldap12.a
-rwxr-x---. 1 oracle oinstall   2919180 Jun 19  2014 libnls12.a
-rwxr-x---. 1 oracle oinstall     24574 Jul  7  2014 libnnet12.a
-rwxr-x---. 1 oracle oinstall     24574 Jul  7  2014 libnnetd12.a
-rwxr-x---. 1 oracle oinstall   1753146 Jun 18  2014 libnnz12.a
-rwxr-x---. 1 oracle oinstall   6213011 Jun 18  2014 libnnz12.so
-rwxr-x---. 1 oracle oinstall  20829764 Jun 18  2014 libnnzst12.a
-rwxr-x---. 1 oracle oinstall     13162 Jun 27  2014 libnoname12.a
-rwxr-x---. 1 oracle oinstall     89737 Jun 27  2014 libnque12.so
-rwxr-x---. 1 oracle oinstall   1022726 Jun 27  2014 libnro12.a
-rwxr-x---. 1 oracle oinstall    217540 Jun 27  2014 libnsgr12.a
-rwxr-x---. 1 oracle oinstall    277530 Jun 27  2014 libntcp12.a
-rwxr-x---. 1 oracle oinstall     13594 Jun 27  2014 libntcpaio12.so
-rwxr-x---. 1 oracle oinstall    307394 Jun 27  2014 libntcps12.a
-rwxr-x---. 1 oracle oinstall    124448 Jun 27  2014 libntmq12.a
-rwxr-x---. 1 oracle oinstall     40130 Jun 27  2014 libntns12.a
-rwxr-x---. 1 oracle oinstall    155584 Jun 27  2014 libnus12.a
-rwxr-x---. 1 oracle oinstall      9958 Jun 27  2014 libnzjs12.a
-rwxr-x---. 1 oracle oinstall   5088996 Jul  7  2014 libocci12.a
lrwxrwxrwx. 1 oracle oinstall        15 Nov  3  2015 libocci.so -> libocci.so.12.1
-rwxr-x---. 1 oracle oinstall   2576046 Nov  3  2015 libocci.so.12.1
-rwxr-x---. 1 oracle oinstall    156353 Jun 30  2014 libocijdbc12.so
-rwxr-x---. 1 oracle oinstall   4059920 Jun 30  2014 libocr12.so
-rwxr-x---. 1 oracle oinstall   7843305 Jun 30  2014 libocrb12.so
-rwxr-x---. 1 oracle oinstall    569688 Jun 30  2014 libocrutl12.so
-rwxr-x---. 1 oracle oinstall     10170 Jul  7  2014 libodm12.a
lrwxrwxrwx. 1 oracle oinstall        12 Nov  3  2015 libodm12.so -> libodmd12.so
-rwxr-x---. 1 oracle oinstall     14605 Jul  7  2014 libodmd12.so
-rwxr-x---. 1 oracle oinstall    868860 Jun 30  2014 liboevm.a
-rwxr-x---. 1 oracle oinstall  36617920 Jul  7  2014 libolapapi12.so
-rwxr-x---. 1 oracle oinstall    426654 Jun 18  2014 libons.a
-rwxr-x---. 1 oracle oinstall    337137 Jun 18  2014 libons.so
-rwxr-x---. 1 oracle oinstall     30755 Jun 18  2014 libonsx.so
-rwxr-x---. 1 oracle oinstall  72957819 Jul  7  2014 libopc12.so
-rwxr-x---. 1 oracle oinstall    117106 Jun 17  2014 liborabz2.a
-rwxr-x---. 1 oracle oinstall    135326 Jul  7  2014 liboramysql12.a
-rwxr-x---. 1 oracle oinstall    118491 Jul  7  2014 liboramysql12.so
-rwxr-x---. 1 oracle oinstall  19817432 Jul  7  2014 liboraolap12.a
-rwxr-x---. 1 oracle oinstall    164452 Jun 17  2014 liboraz.a
-rwxr-x---. 1 oracle oinstall    855612 Jun 19  2014 libordim12.a
-rwxr-x---. 1 oracle oinstall    602152 Jun 19  2014 libordim12.so
-rwxr-x---. 1 oracle oinstall    234006 Jun 19  2014 libordimt12.a
-rwxr-x---. 1 oracle oinstall   8740848 Jun 25  2014 libordsdo12.a
-rwxr-x---. 1 oracle oinstall    137752 Jul  7  2014 liborion12.a
-rwxr-x---. 1 oracle oinstall  72958041 Jul  7  2014 libosbws12.so
-rwxr-x---. 1 oracle oinstall     91568 Jun 18  2014 libowm2.so
-rwxr-x---. 1 oracle oinstall     19860 Jul  7  2014 libpatchgensh12.a
-rwxr-x---. 1 oracle oinstall     20616 Jul  7  2014 libpatchgensh12.so
-rwxr-x---. 1 oracle oinstall    235076 Jul  7  2014 libplc12.a
-rwxr-x---. 1 oracle oinstall    242108 Jul  7  2014 libplc12_pic.a
-rwxr-x---. 1 oracle oinstall   5262112 Jul  7  2014 libplp12.a
-rwxr-x---. 1 oracle oinstall   5319952 Jul  7  2014 libplp12_pic.a
-rwxr-x---. 1 oracle oinstall  13965424 Jul  7  2014 libpls12.a
-rwxr-x---. 1 oracle oinstall  13796608 Jul  7  2014 libpls12_pic.a
-rwxr-x---. 1 oracle oinstall    389414 Jul  7  2014 libpsa12.a
-rwxr-x---. 1 oracle oinstall     24063 Jul  7  2014 libqsmashr.so
-rwxr-x---. 1 oracle oinstall    203424 Jun 30  2014 librdjni12.so
-rwxr-x---. 1 oracle oinstall 326333892 Nov  3  2015 libserver12.a
-rwxr-x---. 1 oracle oinstall   1970920 Jul  7  2014 libshpkavx12.a
-rwxr-x---. 1 oracle oinstall   1818445 Jul  7  2014 libshpkavx12.so
-rwxr-x---. 1 oracle oinstall      4532 Jul  7  2014 libshpkavx212.a
-rwxr-x---. 1 oracle oinstall      8813 Jul  7  2014 libshpkavx212.so
-rwxr-x---. 1 oracle oinstall   2014264 Jul  7  2014 libshpksse4212.a
-rwxr-x---. 1 oracle oinstall   1863576 Jul  7  2014 libshpksse4212.so
-rwxr-x---. 1 oracle oinstall     13906 Nov  3  2015 libskgxn2.so
-rwxr-x---. 1 oracle oinstall     13906 Jul  7  2014 libskgxns.so
-rwxr-x---. 1 oracle oinstall   1135218 Nov  3  2015 libskgxp12.so
-rwxr-x---. 1 oracle oinstall     24795 Jul  7  2014 libskgxpcompat.so
-rwxr-x---. 1 oracle oinstall     24795 Jul  7  2014 libskgxpd.so
-rwxr-x---. 1 oracle oinstall   1135218 Jul  7  2014 libskgxpg.so
-rwxr-x---. 1 oracle oinstall   1135248 Jul  7  2014 libskgxpr.so
-rwxr-x---. 1 oracle oinstall    649944 Jul  7  2014 libskjcx12.so
-rwxr-x---. 1 oracle oinstall     22981 Jul  7  2014 libskvol12.so
-rwxr-x---. 1 oracle oinstall     25676 Jun 18  2014 libslax12.a
-rwxr-x---. 1 oracle oinstall    356272 Jun 19  2014 libsnls12.a
-rwxr-x---. 1 oracle oinstall   1188964 Jul  7  2014 libsql12.a
-rwxr-x---. 1 oracle oinstall   2234110 Jun 18  2014 libsqlplus.a
-rwxr-x---. 1 oracle oinstall   1546540 Jun 18  2014 libsqlplus.so
-rwxr-x---. 1 oracle oinstall   4421284 Jul  7  2014 libsqora.so.12.1
-rwxr-x---. 1 oracle oinstall    195015 Nov  3  2015 libsrvm12.so
-rwxr-x---. 1 oracle oinstall    181808 Jun 30  2014 libsrvm12.so0
-rwxr-x---. 1 oracle oinstall     35515 Jun 30  2014 libsrvmcred12.so
-rwxr-x---. 1 oracle oinstall   1875506 Jun 30  2014 libsrvmhas12.so
-rwxr-x---. 1 oracle oinstall     96029 Jun 30  2014 libsrvmocr12.so
-rwxr-x---. 1 oracle oinstall  10514442 May 23  2014 libsvml.a
-rwxr-x---. 1 oracle oinstall     83062 Jun 30  2014 libuini12.so
-rwxr-x---. 1 oracle oinstall    265906 Jun 19  2014 libunls12.a
-rwxr-x---. 1 oracle oinstall     10030 Jul  7  2014 libvsn12.a
-rwxr-x---. 1 oracle oinstall     10078 Jul  7  2014 libvsn12_cee.a.dbl
-rwxr-x---. 1 oracle oinstall     10070 Jul  7  2014 libvsn12_cse.a.dbl
-rwxr-x---. 1 oracle oinstall     10046 Jul  7  2014 libvsn12_std.a.dbl
-rwxr-x---. 1 oracle oinstall    358124 Jan 31  2013 libwwg.a
-rwxr-x---. 1 oracle oinstall    406094 Jul  7  2014 libxdb.so
-rwxr-x---. 1 oracle oinstall  11448910 Jun 27  2014 libxml12.a
-rwxr-x---. 1 oracle oinstall    192038 Jun 18  2014 libzt12.a
-rwxr-x---. 1 oracle oinstall   4454684 Jun 18  2014 libztkg12.a
-rwxr-x---. 1 oracle oinstall    225972 Jun 19  2014 libzx12.a
-rwxr-x---. 1 oracle oinstall    280984 Oct 23  2001 mail.jar
-rwxr-x---. 1 oracle oinstall     10256 Jun 27  2014 naect.o
-rwxr-x---. 1 oracle oinstall      5576 Jun 27  2014 naedhs.o
-rwxr-x---. 1 oracle oinstall     16416 Jun 27  2014 naeet.o
-rwxr-x---. 1 oracle oinstall      5784 Jun 26  2014 nautab.o
-rwxr-x---. 1 oracle oinstall     18952 Jun 27  2014 nigcon.o
-rwxr-x---. 1 oracle oinstall      5984 Jun 27  2014 nigtab.o
-rwxr-x---. 1 oracle oinstall      1968 Nov  3  2015 nnfgt.o
-rwxr-x---. 1 oracle oinstall      2512 Nov  3  2015 ntcontab.o
-rwxr-x---. 1 oracle oinstall    353883 Jun 26  2014 ojcr.jar
-rwxr-x---. 1 oracle oinstall     19734 Jun  6  2014 okalib.pm
-rwxr-x---. 1 oracle oinstall     22457 Jun  6  2014 okaroot.pl
-rwxr-x---. 1 oracle oinstall      2820 May 23  2014 okatoolsdriver.sh
-rwxr-x---. 1 oracle oinstall    159402 Jun 27  2014 oraclexsql.jar
-rwxr-x---. 1 oracle oinstall     49698 May 23  2014 osds_acfslib.pm
-rwxr-x---. 1 oracle oinstall     47367 May 23  2014 osds_acfsroot.pm
-rwxr-x---. 1 oracle oinstall      2818 May 23  2014 osds_afddriverstate.pm
-rwxr-x---. 1 oracle oinstall      7908 May 23  2014 osds_afdlib.pm
-rwxr-x---. 1 oracle oinstall     25960 May 23  2014 osds_afdroot.pm
-rwxr-x---. 1 oracle oinstall      5000 May 23  2014 osds_okalib.pm
-rwxr-x---. 1 oracle oinstall     22606 May 23  2014 osds_okaroot.pm
-rwxr-x---. 1 oracle oinstall     28427 May 23  2014 osds_unix_linux_acfslib.pm
-rwxr-x---. 1 oracle oinstall      6740 May 23  2014 osds_unix_linux_afdlib.pm
-rwxr-x---. 1 oracle oinstall      3086 May 23  2014 osds_unix_linux_okalib.pm
-rwxr-x---. 1 oracle oinstall      6056 Jun 27  2014 osntabst.o
-rwxr-x---. 1 oracle oinstall      6016 Jun 17  2014 s0main.o
-rwxr-x---. 1 oracle oinstall      3408 Jun 17  2014 scorept.o
-rwxr-x---. 1 oracle oinstall      3120 Jun 17  2014 sscoreed.o
drwxr-x---. 2 oracle oinstall      4096 Nov  3  2015 stubs
-rwxr-x---. 1 oracle oinstall        55 May 23  2014 sysliblist
-rwxr-x---. 1 oracle oinstall    118061 Jun 27  2014 transx.zip
-rwxr-x---. 1 oracle oinstall     12112 Jun 27  2014 xmlcomp2.jar
-rwxr-x---. 1 oracle oinstall     97280 Jun 27  2014 xmlcomp.jar
-rwxr-x---. 1 oracle oinstall    596274 Jun 27  2014 xml.jar
-rwxr-x---. 1 oracle oinstall    679842 Jun 27  2014 xmlmesg.jar
-rwxr-x---. 1 oracle oinstall   1669142 Jun 27  2014 xmlparserv2.jar
-rwxr-x---. 1 oracle oinstall      1816 Jun 27  2014 xmlparserv2_jaxp_services.jar
-rwxr-x---. 1 oracle oinstall   1666571 Jun 27  2014 xmlparserv2_sans_jaxp_services.jar
-rwxr-x---. 1 oracle oinstall    161690 Jun 27  2014 xschema.jar
-rwxr-x---. 1 oracle oinstall      4138 Jun 27  2014 xsqlserializers.jar
-rwxr-x---. 1 oracle oinstall    203755 Jun 27  2014 xsu12.jar

ldd /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so

> 	linux-vdso.so.1 =>  (0x00007fff35d12000)
	libruby.so.2.4 => /opt/sensu/embedded/lib/libruby.so.2.4 (0x00007fa74b64b000)
	libclntsh.so.12.1 => /opt/oracle/12R12/lib/libclntsh.so.12.1 (0x00007fa74868b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa748463000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fa74825b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fa748056000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fa747e1f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa747b9b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa747806000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003555c00000)
	libmql1.so => /opt/oracle/12R12/lib/libmql1.so (0x00007fa747590000)
	libipc1.so => /opt/oracle/12R12/lib/libipc1.so (0x00007fa747212000)
	libnnz12.so => /opt/oracle/12R12/lib/libnnz12.so (0x00007fa746b07000)
	libons.so => /opt/oracle/12R12/lib/libons.so (0x00007fa7468c2000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fa7466a9000)
	libaio.so.1 => /lib64/libaio.so.1 (0x00007fa7464a7000)
	libclntshcore.so.12.1 => /opt/oracle/12R12/lib/libclntshcore.so.12.1 (0x00007fa745f35000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fa745d31000)

readelf -d /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so  | grep rpath

>  0x000000000000000f (RPATH)              Library rpath: [/opt/sensu/embedded/lib:/opt/oracle/12R12/lib]

**Comment by kubo** [comment]
> 0x000000000000000f (RPATH) Library rpath: [/opt/sensu/embedded/lib:/opt/oracle/12R12/lib]

oci8lib_240.so has rpath pointing to /opt/oracle/12R12/lib.

> -rwxrwxrwx. 1 oracle oinstall 58793581 Nov 3 2015 libclntsh.so.12.1

libclntsh.so.12.1 is surely in /opt/oracle/12R12/lib.

> ldd /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.5.1/lib/oci8lib_240.so
>
> > ...
> > libclntsh.so.12.1 => /opt/oracle/12R12/lib/libclntsh.so.12.1 (0x00007fa74868b000)

So oci8lib_240.so should find libclitnsh.so.12.1.
However it failed according to the error message.
Does the user who requires oci8 have permission to read /opt/oracle/12R12/lib?

**Comment by peteralfafara** [comment]
Hi Kubo,

Seems you are right about lack of read permission to /opt/oracle/12R12/. But just to add, the error still persists upon changing permission to have read access. Apparently it requires execution access as well.

old:

> drwxr-x---. 71 oracle oinstall 4096 Jan  8 01:20 12R12

new:

> drwxr-xr-x. 71 oracle oinstall 4096 Jan  8 01:20 12R12

Thanks for the answers! Again, you are very helpful.

Regards,
Peter
