### ISSUE TITLE
Fix for #114 is not working with Rails 5.2 which bundles bootsnap by default

### ISSUE THREAD

**Issue by yahonda** [kubo/ruby-oci8#192]
#### Steps to reproduce

This is originally reported at https://github.com/rails/rails/issues/32811 . It looks like 
Fix for #114 is not working with Rails 5.2 which bundles bootsnap by default.

```ruby
$ rails new myapp -d oracle
$ cd myapp/
$ echo "gem 'ruby-oci8'" >> Gemfile
$ bundle install
$ bundle exec rake -T
Don't require 'ruby-oci8'. Use "require 'oci8'" instead. 'ruby-oci8.rb' was added only for 'Bundler.require'.
rake about                              # List versions of all Rails frameworks and t...
... snip ...
rake yarn:install                       # Install all JavaScript dependencies as spec...
$
```

I expect `Don't require 'ruby-oci8'. Use "require 'oci8'" instead. 'ruby-oci8.rb' was added only for 'Bundler.require'.` should not appear here.

#### Versions:
```ruby
$ rails -v
Rails 5.2.0
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

**Comment by yahonda** [comment]
cc @y-yagi @francescm

**Comment by kubo** [comment]
Thanks for reporting this issue.
I removed the warning.

**Comment by francescm** [comment]
Thank you so much.

**Comment by yahonda** [comment]
Thanks for the fix.
