### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by braham-shakti** [kubo/ruby-oci8#197]
Hi, my oracle client version is `11.2.0.4`

my application is running fine with latest ruby-oci8 gem. 

but as I am using monit to monitor some of process and I got this error

```
/home/ec2-user/.rvm/gems/ruby-1.9.3-p551@ir/gems/ruby-oci8-2.2.5.1/lib/oci8lib_191.so: [BUG] Segmentation fault
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
``` 

Can you please guide me how to fix this error

**Comment by kubo** [comment]
How did you get the error message? Do you have stack trace information?

The following code causes segmentation fault and prints stack trace on ruby 1.9.3-p194. I guess that your ruby also prints stack trace.
```ruby
require 'dl'
DL::CPtr.new(0x123)[0] # This causes segmentation fault.
```

Could you make sample code which reproduces the issue?

**Comment by kubo** [comment]
This issue was closed because of no reply.
If you still have problems, open a new issue.
