### ISSUE TITLE
Failed gem install ver 2.2.7

### ISSUE THREAD

**Issue by JenniferMB** [kubo/ruby-oci8#211]
Message text:

```
Building native extensions. This could take a while...
Successfully installed ruby-oci8-2.2.7
ERROR:  While executing gem ... (NoMethodError)
   undefined method 'source_paths' for #<Gem::Specification:0x7e2408 ruby-oci8-2.2.7>
```
Latest gem file version found on RubyGems.org is dated January 06, 2019. There have been recent commits for this project, have the gem repositories been updated? Could this error I am seeing be resolved by the latest changes dated 10 days ago (as of todays date which is April 02, 2019)

**Comment by kubo** [comment]
What version of ruby and rdoc do you use?
Could you post the output of `ruby --version` and `rdoc --version`?

It works for me.
```
$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
$ rdoc --version
6.1.0
$ gem install ruby-oci8
Fetching ruby-oci8-2.2.7.gem
Building native extensions. This could take a while...
Successfully installed ruby-oci8-2.2.7
Parsing documentation for ruby-oci8-2.2.7
Installing ri documentation for ruby-oci8-2.2.7
Done installing documentation for ruby-oci8 after 1 seconds
1 gem installed
$
```

`ERROR:  While executing gem ... (NoMethodError)` in your comment corresponds to `Parsing documentation for ruby-oci8-2.2.7`. So I guess that the error may be related to rdoc version.

**Comment by JenniferMB** [comment]
My configuration:

```
$ ruby --version
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
$ rdoc --version
6.0.4
$ gem --version
2.5.2.2
```
It is entirely possible that I have an installation-specific issue, but based on my observations as I stated earlier I thought it would be wise to eliminate the possibility of a problem with the gem. If all is well, I will continue with my troubleshooting.

Thank you for your insight, I really appreciate it.
