### ISSUE TITLE
Could not find file (completely broken)

### ISSUE THREAD

**Issue by Bdoom** [kubo/ruby-oci8#220]
Hey Kubo,
I hope your day is going well. I was wondering if you might be able to assist me with an issue with your ruby gem. I work for a company which makes use of your ruby gem for oracle connections and when we upgraded to a new version of Ubuntu 18 there is an issue when trying to load up our puma server. I have an image to show you. However, when I see the error it says the file could not be found, but when I check the directory, the file is in fact there. Maybe you have seen this? 
https://github.com/kubo/ruby-oci8/issues/193  

It looks similar to this issue, perhaps? I will also post this to /issues on your git repository. 
https://i.imgur.com/Wbt8Kq4.png

![image](https://user-images.githubusercontent.com/1284431/64352400-f8241080-cfc9-11e9-8c2c-7b53b94eaa2f.png)

**Comment by Bdoom** [comment]
So I fixed it sort of when adding a new file to /etc/ld.so.conf.d called 'oracle.conf' and then added /opt/instantclient into that file (which is a link to the path) and it seems to boot my server. But now I have a new issue when I try to run rails console. 
![image](https://user-images.githubusercontent.com/1284431/64353222-63baad80-cfcb-11e9-95a6-a3bf41a00cff.png)

**Comment by kubo** [comment]
> oci8.c:561: in oci8lib_220.so: ORA-12170: TNS:Connect timeout occurred (OCIError)

This will not be a ruby-oci8 issue. Could you connect to the server using sqlplus?
If you get same error from sqlplus, see http://www.dba-oracle.com/t_ora_12170_tns_connect_timeout.htm.
