### ISSUE TITLE
Compatibility with macOS Catalina (10.15)

### ISSUE THREAD

**Issue by duffyjp** [kubo/ruby-oci8#221]
<img width="588" alt="Screen Shot 2019-10-15 at 3 21 57 PM" src="https://user-images.githubusercontent.com/382216/66866841-c0609f00-ef5f-11e9-99ac-510dbfa23f68.png">

Is anyone aware of a workaround to get the Oracle Instant Client working in macOS 10.15?  I downloaded the latest version, but it's not signed by Oracle and is being rejected by macOS.

My ancient version of Oracle SQL Developer is working fine, oddly.

**Comment by yahonda** [comment]
I've seen this tweet from @cjbj , it may help your question.

https://twitter.com/ghrd/status/1184238684930863104

**Comment by yahonda** [comment]
https://github.com/oracle/python-cx_Oracle/issues/341#issuecomment-542434282

**Comment by kubo** [comment]
@yahonda Thanks for the helpful information.
I cannot upgrade my macbook to Catalina until the vendor of my network adapter supports it.

**Comment by duffyjp** [comment]
I tried the technique from the twitter link, and it didn't immediately work-- However, after running those commands the dylib did appear in System Preferences -> Security & Privacy where I could allow it.  It didn't appear there previously.  Perhaps both steps are necessary?


After being allowed ruby-oci8 is working just fine. :)

Hopefully Oracle releases a notarized version soon.


Thanks!
