### ISSUE TITLE
Compiling in m1 mac

### ISSUE THREAD

**Issue by ajaya** [kubo/ruby-oci8#231]
Sorry.  This isn't an issue per se and feel free to close it.   Just wondering if anyone has found out a way to compile and install this gem in Apple M1 chip mac?   rvm, brew, ruby install just fine.   But can't get this gem to work.   I know Oracle libraries are all x64.  

Any help?

**Comment by ajaya** [comment]
Just an update that I can run the sqlplus client in arm using Rosetta 2(I think so).  This was installed using brew.

**Comment by kubo** [comment]
I guess that it works if both ruby and ruby-oci8 are all x64.
Compile ruby and ruby-oci8 on intel mac and copies all files to m1 mac.

**Comment by allthesignals** [comment]
Also seeing this on an M1 machine, but unsure because this is the error output I'm seeing: https://github.com/kubo/ruby-oci8/issues/116

**Comment by bragboy** [comment]
it has been two years, any updates on this ?

**Comment by kubo** [comment]
It works when ruby is compiled for x86_64.

In https://github.com/kubo/ruby-oci8/issues/252#issuecomment-1412288318:
> After I switched to x86 version it is able to install the gem.
