### ISSUE TITLE
@tiagobzr I didn't get this..Im getting the same error as cited above

### ISSUE THREAD

**Issue by Prithivi-Raj** [kubo/ruby-oci8#241]
@tiagobzr 
This won't be a ruby-oci8 issue.
Could you connect to the server with the connect string with sqlplus?
```
sqlplus user/password@//host.intranet:1521/SID
```

_Originally posted by @kubo in https://github.com/kubo/ruby-oci8/issues/219#issuecomment-524276832_

**Comment by kubo** [comment]
@Prithivi-Raj 
Could you explain what you asked?
What is "the same error as cited above"?

**Comment by Prithivi-Raj** [comment]
I resolved it xd. Thanks anyways

**Comment by aravindaytha12** [comment]
Hi @Prithivi-Raj, @kubo

I have installed Oracle client based on the below steps
https://medium.com/@arunkundgol/how-to-setup-oracle-instant-client-on-windows-subsystem-for-linux-cccee61d5b0b


**(1)** I have installed 'Oracle Instant Client' in WSL (Windows Subsystem for LINUX, ubuntu)
**(2)** Facing 2 issues while trying from rails console (ruby on rails application)
        - output error: ORA-12162: TNS:net service name is incorrectly specified
        - output error: ORA-12162: Connect failed because target host or object does not exist

**(3)** Even I have mentioned the PATH and ORACLE_HOME Path in '.bashrc' file

export ORACLE_HOME="/opt/oracle/instantclient_19_9" 
export LD_LIBRARY_PATH="/opt/oracle/instantclient_19_9" 
export PATH=$ORACLE_HOME:$PATH
export ORACLE_SID="XD"

Kindly let me know if there anything is missing out here

Regards,
Aravind Aytha
