### ISSUE TITLE
M3 Mac Ruby OCI8 installation issue

### ISSUE THREAD

**Issue by uday708** [kubo/ruby-oci8#260]
I have followed the same steps mentioned in https://www.stufro.com/2023/03/24/mac-m1-oracle-instant-client.html, just my instantclient location different, also tried with exact same path mentioned in blog. Getting the issue

`Building native extensions. This could take a while...
ERROR:  Error installing ruby-oci8:
	ERROR: Failed to build gem native extension.

    current directory: /Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8
/Users/username/.rbenv/versions/jruby-9.4.5.0/bin/jruby -I /Users/username/.rbenv/versions/jruby-9.4.5.0/lib/ruby/stdlib extconf.rb
attempting to locate oracle-instantclient...
checking load library path...
/Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8/oraconf.rb:366: warning: unknown pack directive 'P' in 'P'
  LD_LIBRARY_PATH...
    checking /Users/username/services/oracle_instant_client/19.16.0... no
checking for cc... ---------------------------------------------------
Error Message:
  The compiler failed to generate an executable file.
  You have to install development tools first.

Backtrace:
  /Users/username/.rbenv/versions/jruby-9.4.5.0/lib/ruby/stdlib/mkmf.rb:456:in `try_do'
  /Users/username/.rbenv/versions/jruby-9.4.5.0/lib/ruby/stdlib/mkmf.rb:541:in `try_link0'
  /Users/username/.rbenv/versions/jruby-9.4.5.0/lib/ruby/stdlib/mkmf.rb:864:in `try_run'
  /Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8/oraconf.rb:558:in `check_cc'
  /Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8/oraconf.rb:548:in `init'
  /Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8/oraconf.rb:674:in `initialize'
  org/jruby/RubyClass.java:897:in `new'
  /Users/username/.gem/jruby/3.1.0/gems/ruby-oci8-2.2.12/ext/oci8/oraconf.rb:262:in `get'
  extconf.rb:22:in `<main>'
---------------------------------------------------`

Could anybody help me out with this?

**Comment by uday708** [comment]
@kubo Could you please helm me out with it. Thanks

**Comment by kubo** [comment]
> /Users/username/.rbenv/versions/jruby-9.4.5.0/bin/jruby

JRuby isn't supported because it doesn't support C extensions.
