### ISSUE TITLE
ORA-28041: authentication protocol internal error

### ISSUE THREAD

**Issue by Ethelom** [kubo/ruby-oci8#262]
## Setup
- OS: `Sonoma 14.5`
- Chip: `Apple M2 / M3` (have tried on both)
- Ruby version: `ruby 2.5.5p157 (2019-03-15 revision 67260) [-darwin22]`
- Gem version: `2.2.12`
- Oracle DB version: `19r`
- Oracle Instant Client (_Basic + SDK + SQL*Plus_) version: `23.3` (for [macOS ARM64](https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html))

## Error
Although `bundle install` is successful, when trying to connect the following error occurs:
```
OCIError: ORA-28041: authentication protocol internal error
Help: https://docs.oracle.com/error-help/db/ora-28041/
from oci8.c:603:in oci8lib_250.bundle
```

## Steps to reproduce
```ruby
username = 'YOUR_USERNAME'
password = 'YOUR_PASSWORD'
dsn = 'HOST:PORT/SID'

OCI8.new(username, password, dsn)

# The above error occurs
```

FYI, the same error occurs whether the username + password combination is correct or not.

## Notes
- `OCI_DIR` variable points to the directory where Oracle client is installed
- I have tried configuring `sqlnet.ora` & `tnsnames.ora`, but to no avail
- Connecting with `sqlplus` command line tool works fine.

**Comment by mohits** [comment]
Although you're not on MacOS, I'm adding a link to instructions to get OCI running on Windows also: https://notepad.onghu.com/2021/ruby-oracle-oci-windows-sequel/
