### ISSUE TITLE
Error when using ruby-oci8 with rodauth-rails and sequel-activerecord_connection

### ISSUE THREAD

**Issue by k-graefenhain** [kubo/ruby-oci8#266]
I use rodauth-rails (1.15.0) with sequel-activerecord_connection (1.4.1) and sequel (5.84.0).

When trying to login I get the following error message:
"undefined method `raw_oci_connection' for an instance of OCI8EnhancedAutoRecover"

I tried with ruby-oci8 (2.2.14) and (2.2.13 x64-mingw-ucrt). Any suggestions how I can solve the issue?

**Comment by kubo** [comment]
Could you post this issue to another project with [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I don't think that this is a ruby-oci8 issue.

The class `OCI8EnhancedAutoRecover` in the error message isn't a class of ruby-oci8.
sequel-activerecord_connection doesn't support Oracle officially. In the [README](https://github.com/janko/sequel-activerecord_connection):

> there is attempted support for [Oracle enhanced](https://github.com/rsim/oracle-enhanced) (oracle and in Sequel)
