### ISSUE TITLE
Integers being converted to BigDecimal vs Number

### ISSUE THREAD

**Issue by jadon1979** [kubo/ruby-oci8#33]
I have a table with a column named "display_order".  This Number type is being converted within oci8 upon fetch and/or fetch_hash.

display_order 123 becomes "123.0"

**Comment by tallenaz** [comment]
Can we fix this in the display?

**Comment by kubo** [comment]
@tallenaz 
1. Could you open a new issue? Your issue looks unrelated to this one.
2. Could you explain more details? I cannot imagine what you requested.

**Comment by tallenaz** [comment]
Sorry for the noise @kubo, I'll open a new issue if necessary.
