### ISSUE TITLE
OCI8.new hangs intermittently

### ISSUE THREAD

**Issue by andyioannou** [kubo/ruby-oci8#45]
Experiencing an intermittent issue when executing OCI8.new(<dbinfo>) 

I can (intermittently) reproduce in the rails console
bash-3.2$ rails c
Loading development environment (Rails 3.0.9)
1.9.3-p448 :001 > OCI8.new(<dbinfo>)

or from the command line 
$ruby -rubygems -e "require 'oci8'; OCI8.new(<dbinfo>)

in either case the command hangs and simple does not return (I have to kill the process)

Here is some info on versions
rails: 3.0.9
ruby: 1.9.3p448
ruby-oci8: 2.1.0 
Oracle Instant Client: 12.1 64bit

If I kill the process and try OCI8.new(<dbinfo>) again it will often start working and return the connection, which then works perfectly (.exec works etc). After OCI8.new has worked once I can continue to create new connections without problem. Then ... at some point in the future .. usually after being idle for some time the same issue will be encountered (a new OCI8.new(<dbinfo>) fails to return)

I have tested the target machine hosting the db is accessible (ping / traceroute etc) during the times when OCI8 hangs. Also I can call OCI8.new with the wrong login details and it will come back with an authentication error, but a call with the correct login details straight after can hang.

So
1) are there any know incompatibilities between the oci8 version and other components listed
2) How would you suggest debugging this? I am trying to establish what is going on at the point of hanging. Is it in OCI8 or is this simply a network issue (seems unlikely to be purely network because I can always get the db to give me an authentication error - it never fails to return).
3) Is there some way of configuring OCI8 to 'timeout' if it is waiting for something (I don't know this is the problem - but it could be.

Thanks for your help

**Comment by kubo** [comment]
The next ruby-oci8 release includes timeout parameters.
See http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/timeout-parameters.md.
Use these parameters for low-quality networks.
