### ISSUE TITLE
cannot open shared object file: oci8lib_191.so 

### ISSUE THREAD

**Issue by redbull-assassin** [kubo/ruby-oci8#46]
This happens everytine I try to use the oci8 gem, but the file it cannot find exists
1.9.3-p448 :001 > require 'oci8'
LoadError: libaio.so.1: cannot open shared object file: No such file or directory - /usr/local/rvm/gems/ruby-1.9.3-p448/gems/ruby-oci8-2.1.5/lib/oci8lib_191.so
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/ruby-oci8-2.1.5/lib/oci8.rb:81:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in`require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
        from (irb):1
        from /usr/local/rvm/rubies/ruby-1.9.3-p448/bin/irb:13:in `<main>'
1.9.3-p448 :002 > exit
root@hydra:/usr/local/lib/instantclient# ls -la /usr/local/rvm/gems/ruby-1.9.3-p448/gems/ruby-oci8-2.1.5/lib/oci8lib_191.so
-rwxr-xr-x 1 root rvm 678393 Nov 24 21:13 /usr/local/rvm/gems/ruby-1.9.3-p448/gems/ruby-oci8-2.1.5/lib/oci8lib_191.so

**Comment by davidsun2016** [comment]
I met same error on windows environment, load error for oci8lib_200.so,  what should I do? thanks!
