### ISSUE TITLE
Nonblocking logon/logoff

### ISSUE THREAD

**Issue by kmehkeri** [kubo/ruby-oci8#54]
Is it possible to login/logoff in a nonblocking way? Nonblocking mode described in documentation seems to be working only for queries.

As a workaround following works for me on logon, allowing me to abort with CTRL+C in case of network issues, etc.:

```
# Delegate login to a separate thread as OCI8.new seems to ignore interrupts
begin
  thread = Thread.new { @oci = OCI8.new(credentials) }
  thread.join
rescue Interrupt
  thread.exit
  raise
end
```

For logoff, this doesn't even work. Interrupt is caught, but both thread.exit and Kernel.exit hang. Only Kernel.exit! allows me to shut down, but I suppose that's not too clean. I wonder if it's a bug or I'm doing something wrong?

**Comment by kubo** [comment]
FYI. The next ruby-oci8 release includes timeout parameters.
They are equivalent to parameters in `sqlnet.ora`.
See http://www.rubydoc.info/github/kubo/ruby-oci8/file/docs/timeout-parameters.md.
