### ISSUE TITLE
can oci8 support chinese chartset, how can i config it?

### ISSUE THREAD

**Issue by kinghw** [kubo/ruby-oci8#68]
my oracle env is like this 
NLS_LANG=AMERICAN_AMERICA.AL32UTF8
LANG=en_US.UTF-8

when i insert an chinese char ,it will be '?????'
but i use oracle client like navicat to insert chinese it's ok

i don'n know how to fix it? thanks for help

**Comment by kubo** [comment]
What is the encoding of the chinese chracter?
What ruby version do you use?

If you use ruby 1.9 or upper, ruby-oci8 and Oracle TNS layer change the encoding.
Ruby-oci8 sets [`OCI8.encoding`](https://github.com/kubo/ruby-oci8/blob/5d70c056de6a04f8a0ac209e86f91f7e6d33bbc8/ext/oci8/encoding.c#L222) from NLS_LANG on startup according to [encoding.yml](https://github.com/kubo/ruby-oci8/blob/master/lib/oci8/encoding.yml)
When string encoding (check it by [String#encoding](http://www.rubydoc.info/stdlib/core/String:encode) is different from `OCI8.encoding`, ruby-oci8 converts it to `OCI8.encoding` before it is passed to Oracle client library.
If client NLS_LANG is differenct from the database encoding, Oracle TNS layer converts it to the
database encoding.
Could you check `OCI8.encoding` and whether `String#encoding` is correctly set?

If you use ruby 1.8, you must use UTF-8 string when NLS_LANG is AMERICAN_AMERICA.AL32UTF8.
If you use chinese encoding such as GB18030, the last part of NLS_LANG must be ZHS32GB18030, not 'AL32UTF8'.

**Comment by kinghw** [comment]
@kubo thanks, i solve it with setting client nls_lang env same as oracle server
