### ISSUE TITLE
Says to "Install 'Oracle Call Interface' component." when everything has been installed properly on OS X 10.10.2.

### ISSUE THREAD

**Issue by jhubbardsf** [kubo/ruby-oci8#72]
I'm trying to install this gem. Have installed everything for instant client on my computer and can sqlplus connect to my virtual Oracle server. 

When I try to install this Gem I get 

`Error Message:
  '/usr/local/oracle/product/instantclient_64/11.2.0.3.0/rdbms/public/oci.h' does not exists. Install 'Oracle Call Interface' component.`

However I installed everything for OS X OCI, mainly using these [these instructions.](https://coderwall.com/p/nvva7a/setup-oracle-instant-client-and-ruby-oci8-gem-on-mac) Although I read the official installation instructions for everything and they match perfectly. Like I said, I can sqlplus from my Mac to my Oracle VM (running on same Mac). I feel like this issue is with ruby-oci8 since I can connect fine, I'm only getting this error on Gem install.

**Comment by kubo** [comment]
[The instructions](https://coderwall.com/p/nvva7a/setup-oracle-instant-client-and-ruby-oci8-gem-on-mac) are not good. They put Oracle instant client files in directory hierarchy similar to Oracle full client even though it isn't a full client. It confuses ruby-oci8.

Look at [these instructions](http://stackoverflow.com/questions/11894194/how-to-install-ruby-oci8/21443313#21443313) instead.

**Comment by jhubbardsf** [comment]
Odd, I realized I had downloaded the 32bit version of the IC. I hadn't seen your reply yet so I just redid my original instructions with the 64bit version and everything worked. I'm not sure if I messed something up originally or it was the 32bit version. But it's working now. You can close this, thinks for the quick response.
