### ISSUE TITLE
Use OCIStmtPrepare2 for all statements

### ISSUE THREAD

**Issue by cjbj** [kubo/ruby-oci8#77]
This is just to give a nudge about upgrading an older OCI API call. There are a mix of OCIStmtPrepare and OCIStmtPrepare2 calls in the code.  The latter is newer and supports Oracle's statement cache and oraaccess.xml features.

**Comment by kubo** [comment]
Thanks for the information.
I noticed that OCIStmtPrepare had been unreachable code since https://github.com/kubo/ruby-oci8/commit/663fe575f67916da6c55b727fd3263d4b98652d0#diff-dd781a91f41f206a4c3e065e4ff30663.
I dropped the code just now by c1655d422a667931918be6167e46fa4833de47e6.
