### ISSUE TITLE
When I run the `oci8` gem, I get “OCI Library Initialization Error”

### ISSUE THREAD

**Issue by chrismp** [kubo/ruby-oci8#78]
When I run `require 'oci8'`, I get this error:

```
oci8lib.c:141:in oci8lib_191.so: OCI Library Initialization Error - C:\Ruby193\bin\OCI.DLL (OCIError)
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-oci8-2.1.8-x86-mingw32/lib/oci8.rb:70:in `<top (required)>'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
```

This comes after I downloaded the 32-bit `instantclient-basic-nt-12.1.0.2.0.zip` from [this Oracle page](http://www.oracle.com/technetwork/topics/winsoft-085727.html) and put `oci.dll` in `C:\Ruby193\bin`.

I'm running Ruby 1.9.3 with Windows 7 on a 64-bit machine.

UPDATE: I copied ALL `.dll` files from Oracle's 32-bit [Instant Client download page](http://www.oracle.com/technetwork/topics/winsoft-085727.html) and put them in `C:\Ruby193\bin\`. 

Now I get this message:
`Warning: NLS_LANG is not set. fallback to US7ASCII.`

**Comment by kubo** [comment]
> Now I get this message:
> Warning: NLS_LANG is not set. fallback to US7ASCII.

You need to set the environment variable NLS_LANG to tell ruby-oci8 the Oracle client character set.
See http://www.orafaq.com/wiki/NLS_LANG

**Comment by chrismp** [comment]
That did it. Thanks!

**Comment by AJFaraday** [comment]
@kubo I've just had this issue and the NLS_LANG attribute fixed it, thanks!

**Comment by Farrukh-Sarmad** [comment]
What value should I set to NLS_LANG variable?

**Comment by kubo** [comment]
@Farrukh-Sarmad 
This issue includes two different issues.
One is "OCI Library Initialization Error". It was fixed by putting **all** DLL files from an instant client package to one directory.
The other is "Warning: NLS_LANG is not set. fallback to US7ASCII." It was fixed by setting the environment variable NLS_LANG. The value you should set depends on language, territory and character set you use. Ask google about it.
