### ISSUE TITLE
Mac Instant Client installation instructions

### ISSUE THREAD

**Issue by kaukas** [kubo/ruby-oci8#84]
Hello.

Thank you for the great library to interface Oracle from Ruby! The one pain point I still had was the Instant Client installation and ruby-oci8 compilation. Particularly on Mac, since there was no automatic way.

There is a [Brew tap](https://github.com/InstantClientTap/homebrew-instantclient) to help install Instant Client on Mac. It is very crude but should simplify the simple case a lot. Do you think it would make sense to mention it in the [Mac installation docs](https://github.com/kubo/ruby-oci8/blob/master/docs/install-instant-client.md)?

Thank you!

**Comment by kubo** [comment]
Thank you!
I updated the installation document.
