### ISSUE TITLE
Invalid Svcctx reading OCI8::CLOB

### ISSUE THREAD

**Issue by GPardal** [kubo/ruby-oci8#88]
Hello everyone,

I've been having some troubles while trying to read a OCI8::CLOB. My code is simple:

`notification.first['MESSAGE'].read`

I've had some success in reading the message before, but now I'm getting Invalid Svcctx errors. I've tried digging in the Ruby-OCI8 source, but can't understand the validations that make the error popup:

    if (svcctx == NULL || svcctx->base.type != OCI_HTYPE_SVCCTX) {
        rb_raise(rb_eRuntimeError, "Invalid Svcctx");
    }

Does anyone know what could be the problem? I'm currently using ruby-oci8 (2.1.2) with ruby 1.9.3p551 and Oracle 10.2.0.5.0.

Thanks for the help.

**Comment by kubo** [comment]
Could you more detailed code to reproduce the issue.
Does your code reads a LOB after logoff?

I ran the following script with various ruby-oci8 versions.
```ruby
require 'oci8'

conn = OCI8.new('ruby/oci8')
conn.exec('drop table test_issue_88 purge') rescue nil
conn.exec('create table test_issue_88 (clob_col clob)')
conn.exec('insert into test_issue_88 values (:1)', '123456')
conn.commit
lob = conn.select_one('select clob_col from test_issue_88')[0]
conn.logoff
puts 'try to read lob after logoff'
p lob.read
```
The results are:

ruby-oci8 version| result
---|---
2.1.2|invalid argument NilClass (expect OCI8) (TypeError)
2.1.3|invalid argument NilClass (expect OCI8) (TypeError)
2.1.4|invalid argument NilClass (expect OCI8) (TypeError)
2.1.5|Invalid Svcctx (RuntimeError)
2.1.6|Invalid Svcctx (RuntimeError)
2.1.7|Invalid Svcctx (RuntimeError)
2.1.8|OCI8::CLOB was already closed. (OCIException)

**Comment by GPardal** [comment]
Hello Kubo, thanks for the fast reply.

Yes, my code tries to read the LOB after the logoff. Is this wrong? I see that none of the results you showed had the expected result. 

In any case, here a snippet of my code, with the relevant code highlighted:

`oci = OCI8.new(con_info[:username], con_info[:password], tnsnames)
[...]
notification = oci.exec(query)
oci.logoff
[...]
if notification.is_a?(Array) and notification.first.is_a?(Hash)
  return notification.first['TEXT'] unless notification.first['TEXT'].nil?
  return notification.first['MESSAGE'].read`

I don't have access to the environment the following week, but as soon as I can, I will try to check if the read works before I logoff the connection. Do you think that might be the problem?

Thanks.

**Comment by kubo** [comment]
When a LOB is read, its contents are fetched from the Oracle server via the connection.
If the connection is closed, the LOB cannot be read.

**Comment by GPardal** [comment]
That is probably it, then. I was thinking the LOB would be loaded on the query execution, and could be read anytime after logoff.

I still don't have access to the environment I was using, but as soon as I can, I will post the results here.

**Comment by GPardal** [comment]
Hey there kubo,

I'm just commenting to confirm that your idea was correct. I was closing the connection before the read. After I fixed that, the behaviour was as expected.

Thanks so much for the help, and sorry for the delay.

Cheers!

**Comment by kubo** [comment]
Okay. I close this issue.

I updated the OCI8::LOB document as 102638fe11115687ea797e51aa725658c3764840.
