### ISSUE TITLE
MRI process locks up in OCI handle GC

### ISSUE THREAD

**Issue by mperham** [kubo/ruby-oci8#90]
https://gist.github.com/Dharshi/ec55411d24f9fd153f01#file-gistfile1-txt-L1186

It would appear that Thread 9 is trying to get a native lock while holding the GVL.  This means that no other Ruby threads can execute while waiting for the native lock.  Rule of thumb: you should never wait on a native lock while holding the GVL.

I should explain: this results in the entire MRI process locking up and unable to perform any work.

**Comment by kubo** [comment]
Ruby-oci8 2.1.6 or 2.1.7 was used according to the backtrace.
The issue was fixed by 84c1cab6c74e0949e40c4a29e89c971b1ae11bce. Use ruby-oci8 2.1.8 instead.
