### ISSUE TITLE
Passing TCP Socket class to initialization

### ISSUE THREAD

**Issue by TiagoCardoso1983** [kubo/ruby-oci8#92]
Coming from here: https://groups.google.com/forum/#!topic/sequel-talk/jdvvqcsH6Fg

Is there already the possibility of passing the tcp socket class to the constructor (or an open socket)? Something like: 

```ruby
conn = OCI8.connect( 'scott', 'tiger', tcp_socket_class: Celluloid::IO::TCPSocket )
```

Other implementations could potentially benefit from this, as em-synchrony has its own tcp socket duck types.

**Comment by kubo** [comment]
It can't. Oracle client library doesn't accept a socket to establish a connection and doesn't expose a socket of an established connection.

**Comment by TiagoCardoso1983** [comment]
Would it be something worthy of a merge request? Or is there any hinderance of some kind?

**Comment by kubo** [comment]
Ruby-oci8 uses Oracle client library provided by Oracle Corporation. Ruby-oci8 can do nothing unless Oracle Corporation changes the Oracle client library to accept or expose a socket.
